def P(title, text, qs): return dict(title=title, text=text, qs=qs)
# Mỗi chặng: A (2 bài đọc × 5 câu), AV (từ ngữ theo chủ điểm), W (danh từ / động từ / tính từ),
# TC (luyện từ theo bài học), CT (chính tả: đúng, sai), CAU (trạng ngữ, loại TN, chủ ngữ, vị ngữ),
# ORD (xếp câu), PUNCT (câu có ☐, dấu đúng, các lựa chọn hoặc None = . ? !)
U = []

# ===================== TẬP 1 · MỖI NGƯỜI MỘT VẺ =====================
U.append(dict(lab='Chặng 1', t='Điều kì diệu · Thi nhạc · Anh em sinh đôi · Công chúa và người dẫn chuyện', vn='Bài 1 – 4 · Tập 1 · Mỗi người một vẻ',
 A=[P('Lớp học có mười bảy màu áo', 'Lớp 4B có mười bảy bạn, mỗi bạn một vẻ. Minh ít nói nhưng vẽ rất đẹp, bức tranh cánh đồng lúa của bạn được treo ở góc lớp. Hà nói nhanh như sáo, lúc nào cũng có chuyện vui để kể. Tuấn mê đá bóng, còn Thảo thích trồng cây, ô cửa sổ lớp nào cũng có chậu hoa của bạn ấy. Cô giáo bảo: “Mỗi em là một bông hoa. Không bông nào giống bông nào, nhưng bông nào cũng thơm.” Từ hôm đó, cả lớp thôi so bì với nhau mà biết quý điểm riêng của từng bạn.',
   [('Lớp 4B có bao nhiêu bạn?', 'Mười bảy bạn', ['Mười lăm bạn', 'Hai mươi bạn']),
    ('Minh có điểm gì đặc biệt?', 'Ít nói nhưng vẽ rất đẹp', ['Nói nhanh như sáo', 'Mê đá bóng']),
    ('Bạn nào thích trồng cây?', 'Thảo', ['Hà', 'Tuấn']),
    ('Cô giáo so sánh mỗi bạn với gì?', 'Một bông hoa', ['Một vì sao', 'Một cái cây']),
    ('Câu chuyện muốn nói điều gì?', 'Mỗi người có một vẻ riêng đáng quý', ['Ai cũng phải giống nhau', 'Chỉ bạn học giỏi mới đáng quý'])]),
  P('Hai anh em sinh đôi', 'Khoa và Khôi là anh em sinh đôi. Hai bạn giống nhau như hai giọt nước nên thường bị nhầm tên. Khoa mặc cảm lắm, chỉ mong mọi người nhận ra mình. Một lần, Khoa đứng lên phát biểu rất sôi nổi về cách chăm sóc cây xanh. Cô giáo khen: “Khoa suy nghĩ thật sâu sắc!” Khoa chợt hiểu: hai anh em giống nhau về dáng hình, nhưng mỗi người có suy nghĩ, sở thích riêng. Chính điều đó giúp mọi người nhận ra mình.',
   [('Khoa và Khôi là gì của nhau?', 'Anh em sinh đôi', ['Bạn cùng xóm', 'Anh em họ']),
    ('Vì sao hai bạn thường bị nhầm tên?', 'Vì giống nhau như hai giọt nước', ['Vì tên giống hệt nhau', 'Vì học khác lớp']),
    ('Khoa phát biểu về chủ đề gì?', 'Cách chăm sóc cây xanh', ['Cách nuôi cá cảnh', 'Cách chơi cờ vua']),
    ('Cô giáo khen Khoa điều gì?', 'Suy nghĩ thật sâu sắc', ['Chữ viết thật đẹp', 'Chạy thật nhanh']),
    ('Khoa hiểu ra điều gì?', 'Mỗi người có suy nghĩ, sở thích riêng', ['Phải bắt chước anh', 'Không nên phát biểu'])])],
 AV=[('Từ nào có nghĩa là “vẻ riêng, không giống ai”?', 'Độc đáo', ['Bình thường', 'Giống hệt']),
     ('Câu “Mỗi người một vẻ” có ý nghĩa gì?', 'Mỗi người có nét riêng', ['Mọi người đều giống nhau', 'Ai cũng xinh đẹp']),
     ('Người có năng khiếu âm nhạc thường giỏi việc gì?', 'Hát, chơi đàn', ['Vẽ bản đồ', 'Sửa xe đạp']),
     ('Từ nào chỉ tính nết của người luôn nói thật?', 'Trung thực', ['Nhút nhát', 'Kiêu căng']),
     ('Người dẫn chuyện trong một vở kịch làm nhiệm vụ gì?', 'Kể, giới thiệu diễn biến câu chuyện', ['Đóng vai nhân vật chính', 'Kéo rèm sân khấu']),
     ('Khi biểu diễn hồi hộp, run sợ, em nên làm gì?', 'Hít thở sâu và cố gắng hết mình', ['Bỏ chạy khỏi sân khấu', 'Trách bạn diễn cùng'])],
 W=dict(dt=['học sinh', 'bông hoa', 'cô giáo', 'bức tranh', 'sân khấu', 'chiếc đàn'], dgt=['phát biểu', 'biểu diễn', 'trồng', 'kể', 'hát', 'chạy'], tt=['sâu sắc', 'độc đáo', 'sôi nổi', 'hiền lành', 'thơm', 'nhanh nhẹn']),
 TC=[('Danh từ là gì?', 'Từ chỉ sự vật (người, vật, hiện tượng, khái niệm…)', ['Từ chỉ hoạt động, trạng thái', 'Từ chỉ đặc điểm, tính chất']),
     ('Từ nào là danh từ riêng?', 'Hà Nội', ['thành phố', 'dòng sông']),
     ('Từ nào là danh từ chung?', 'ngọn núi', ['Trường Sơn', 'Hồng Hà']),
     ('Danh từ riêng được viết như thế nào?', 'Viết hoa', ['Viết thường', 'Viết nghiêng']),
     ('Từ nào là danh từ chỉ hiện tượng tự nhiên?', 'cơn mưa', ['cái bàn', 'thầy giáo']),
     ('Từ nào là danh từ chỉ đơn vị?', 'chiếc', ['đẹp', 'chạy']),
     ('Trong câu “Minh vẽ bức tranh cánh đồng.”, danh từ riêng là:', 'Minh', ['bức tranh', 'cánh đồng'])],
 CT=[('sáng tạo', 'sáng tạu'), ('xôn xao', 'sôn sao'), ('trình diễn', 'chình diễn'), ('giọng hát', 'dọng hát'), ('sân khấu', 'xân khấu'), ('rực rỡ', 'rực rở'), ('Hà Nội', 'Hà nội')],
 CAU=[('', '', 'Minh', 'vẽ tranh rất đẹp.'), ('', '', 'Hai anh em', 'giống nhau như hai giọt nước.'), ('', '', 'Cô giáo', 'khen Khoa suy nghĩ sâu sắc.'),
      ('', '', 'Chậu hoa của Thảo', 'nở rực rỡ bên cửa sổ.'), ('', '', 'Tiếng đàn', 'vang lên trong trẻo.'), ('', '', 'Các bạn lớp 4B', 'biểu diễn văn nghệ.')],
 ORD=[['Mỗi', 'người', 'có', 'một', 'vẻ riêng.'], ['Hà', 'kể', 'chuyện', 'rất', 'vui.'], ['Thảo', 'thích', 'trồng', 'cây', 'xanh.'], ['Cả lớp', 'vỗ tay', 'khen', 'Minh.'], ['Khoa', 'phát biểu', 'rất', 'sôi nổi.']],
 PUNCT=[('Bạn thích làm gì nhất ☐', '?', None), ('Ôi, bức tranh đẹp quá ☐', '!', None), ('Hà nói nhanh như sáo ☐', '.', None), ('Vì sao bạn thích trồng cây ☐', '?', None), ('Chao ôi, tiếng đàn hay quá ☐', '!', None), ('Mỗi bạn trong lớp đều có điểm đáng quý ☐', '.', None)]))

U.append(dict(lab='Chặng 2', t='Thằn lằn xanh và tắc kè · Nghệ sĩ trống · Những bức chân dung · Đò ngang', vn='Bài 5 – 8 · Tập 1 · Mỗi người một vẻ',
 A=[P('Tắc kè và thằn lằn', 'Thằn lằn xanh và tắc kè là đôi bạn thân. Thằn lằn thích chạy nhảy dưới ánh nắng ban ngày, còn tắc kè lại thích đi kiếm ăn vào ban đêm. Có lần, thằn lằn rủ tắc kè ra sưởi nắng. Tắc kè nheo mắt khó chịu, bò vội vào hốc cây. Thằn lằn buồn lắm. Bác cú mèo bảo: “Mỗi loài có một thói quen riêng. Bạn bè hiểu và tôn trọng nhau thì mới thân lâu được.” Từ đó, hai bạn hẹn gặp nhau lúc chiều tà, khi nắng đã dịu.',
   [('Thằn lằn thích làm gì?', 'Chạy nhảy dưới ánh nắng ban ngày', ['Kiếm ăn ban đêm', 'Ngủ suốt ngày']),
    ('Tắc kè thường kiếm ăn vào lúc nào?', 'Ban đêm', ['Buổi trưa', 'Sáng sớm']),
    ('Khi ra nắng, tắc kè làm gì?', 'Bò vội vào hốc cây', ['Nằm sưởi rất lâu', 'Chạy nhảy vui vẻ']),
    ('Bác cú mèo khuyên điều gì?', 'Bạn bè cần hiểu và tôn trọng nhau', ['Phải bắt bạn giống mình', 'Không nên chơi với ai']),
    ('Hai bạn hẹn gặp nhau khi nào?', 'Lúc chiều tà', ['Giữa trưa', 'Nửa đêm'])]),
  P('Cô bé đánh trống', 'Mai là tay trống nhỏ nhất đội nghi lễ của trường. Chiếc trống to gần bằng người, nhưng đôi tay Mai gõ rất đều và chắc. Buổi tập đầu, Mai đánh lệch nhịp khiến cả đội phải dừng lại. Mai đỏ mặt, nhưng không bỏ cuộc. Tối nào Mai cũng gõ nhịp lên mặt bàn, vừa gõ vừa đếm. Đến ngày khai giảng, tiếng trống của Mai vang lên rộn rã, dẫn đầu đoàn diễu hành. Thầy phụ trách mỉm cười: “Em đúng là một nghệ sĩ trống!”',
   [('Mai là ai trong đội nghi lễ?', 'Tay trống nhỏ nhất', ['Đội trưởng', 'Người cầm cờ']),
    ('Chiếc trống của Mai thế nào?', 'To gần bằng người', ['Nhỏ như cái bát', 'Làm bằng giấy']),
    ('Buổi tập đầu Mai gặp chuyện gì?', 'Đánh lệch nhịp', ['Làm rách trống', 'Đến muộn']),
    ('Mai đã tập luyện thế nào?', 'Tối nào cũng gõ nhịp và đếm', ['Bỏ tập vài hôm', 'Chỉ xem bạn tập']),
    ('Thầy khen Mai là gì?', 'Một nghệ sĩ trống', ['Một học sinh giỏi toán', 'Một vận động viên'])])],
 AV=[('Từ nào gần nghĩa với “kiên trì”?', 'Bền bỉ', ['Nản lòng', 'Vội vàng']),
     ('Bức chân dung là bức tranh vẽ gì?', 'Khuôn mặt, hình dáng một người', ['Phong cảnh núi sông', 'Đồ vật trên bàn']),
     ('Đò ngang dùng để làm gì?', 'Chở người qua sông', ['Đánh bắt cá xa bờ', 'Chở hàng ra biển lớn']),
     ('Thành ngữ “Cá mè một lứa” nói về điều gì?', 'Những người giống nhau, cùng loại', ['Người rất giỏi bơi', 'Người thích ăn cá']),
     ('Người chơi nhạc cụ giỏi, biểu diễn hay được gọi là gì?', 'Nghệ sĩ', ['Kĩ sư', 'Bác sĩ']),
     ('Từ nào chỉ đức tính của người lái đò tận tuỵ?', 'Chu đáo', ['Cẩu thả', 'Lười nhác'])],
 W=dict(dt=['chiếc trống', 'đội nghi lễ', 'bến sông', 'con đò', 'hốc cây', 'bức chân dung'], dgt=['gõ', 'đếm', 'diễu hành', 'chèo', 'sưởi', 'nhảy'], tt=['rộn rã', 'bền bỉ', 'chắc chắn', 'khó chịu', 'dịu', 'đều đặn']),
 TC=[('Tên cơ quan, tổ chức được viết hoa như thế nào?', 'Viết hoa chữ cái đầu của mỗi bộ phận tạo thành tên', ['Viết hoa tất cả các chữ cái', 'Không cần viết hoa']),
     ('Tên tổ chức nào viết đúng?', 'Đội Thiếu niên Tiền phong Hồ Chí Minh', ['Đội thiếu niên tiền phong Hồ Chí Minh', 'đội Thiếu Niên Tiền Phong hồ chí minh']),
     ('Tên cơ quan nào viết đúng?', 'Trường Tiểu học Nguyễn Trãi', ['trường tiểu học Nguyễn Trãi', 'Trường tiểu học nguyễn trãi']),
     ('Tên nào viết đúng?', 'Thư viện Quốc gia Việt Nam', ['Thư Viện quốc gia việt nam', 'thư viện Quốc gia Việt nam']),
     ('Động từ là gì?', 'Từ chỉ hoạt động, trạng thái của sự vật', ['Từ chỉ tên gọi của sự vật', 'Từ chỉ màu sắc, hình dáng']),
     ('Từ nào là động từ chỉ trạng thái?', 'ngủ', ['gõ', 'nhảy']),
     ('Trong câu “Mai gõ trống rất đều.”, động từ là:', 'gõ', ['trống', 'đều'])],
 CT=[('chèo đò', 'trèo đò'), ('chân dung', 'trân dung'), ('diễu hành', 'giễu hành'), ('tắc kè', 'tắc ke'), ('lặng lẽ', 'lặng lẻ'), ('sưởi nắng', 'xưởi nắng'), ('Đội Thiếu niên Tiền phong', 'Đội thiếu niên tiền phong')],
 CAU=[('', '', 'Thằn lằn xanh', 'thích sưởi nắng.'), ('', '', 'Tiếng trống của Mai', 'vang lên rộn rã.'), ('', '', 'Bác lái đò', 'chèo thuyền qua sông.'),
      ('', '', 'Họa sĩ', 'vẽ chân dung cô bé.'), ('', '', 'Tắc kè', 'kiếm ăn vào ban đêm.'), ('', '', 'Cả đội nghi lễ', 'tập luyện chăm chỉ.')],
 ORD=[['Tiếng trống', 'vang lên', 'rộn rã.'], ['Bác lái đò', 'đưa', 'khách', 'qua sông.'], ['Thằn lằn', 'và', 'tắc kè', 'là', 'bạn thân.'], ['Mai', 'không', 'bỏ cuộc.'], ['Hoạ sĩ', 'vẽ', 'bức chân dung', 'rất đẹp.']],
 PUNCT=[('Bạn có muốn qua sông không ☐', '?', None), ('Tiếng trống vang lên rộn rã ☐', '.', None), ('Ôi, bức chân dung giống quá ☐', '!', None), ('Mai tập đánh trống mỗi tối ☐', '.', None), ('Chà, con đò chạy nhanh thật ☐', '!', None), ('Ai là tay trống nhỏ nhất đội ☐', '?', None)]))

# ===================== TẬP 1 · TRẢI NGHIỆM VÀ KHÁM PHÁ =====================
U.append(dict(lab='Chặng 3', t='Bầu trời trong quả trứng · Tiếng nói của cỏ cây · Tập làm văn · Nhà phát minh 6 tuổi', vn='Bài 9 – 12 · Tập 1 · Trải nghiệm và khám phá',
 A=[P('Chú gà con phá vỏ', 'Bé Na ngồi bên ổ trứng suốt buổi chiều. Bỗng một quả trứng khẽ rung rinh. Tiếng “cốc, cốc” nhỏ xíu vang lên. Một chiếc mỏ vàng nhọn hoắt mổ thủng lớp vỏ. Chú gà con loay hoay mãi mới chui ra được, lông ướt dính vào người. Chỉ lát sau, bộ lông khô lại, bông lên như một nắm tơ vàng. Chú kêu “chiếp, chiếp” rồi ngơ ngác nhìn quanh. Na thầm nghĩ: trước kia, bầu trời của chú chỉ là lớp vỏ trứng bé tí, giờ chú đã thấy cả một thế giới rộng lớn.',
   [('Bé Na ngồi bên ổ trứng khi nào?', 'Suốt buổi chiều', ['Sáng sớm', 'Nửa đêm']),
    ('Chú gà con dùng gì để phá vỏ trứng?', 'Chiếc mỏ', ['Đôi chân', 'Đôi cánh']),
    ('Khi lông khô, bộ lông chú gà giống gì?', 'Một nắm tơ vàng', ['Một đám mây đen', 'Một chiếc lá khô']),
    ('Tiếng kêu của chú gà con là gì?', 'Chiếp, chiếp', ['Ò ó o', 'Cục tác']),
    ('“Bầu trời” trước kia của chú gà là gì?', 'Lớp vỏ trứng', ['Chuồng gà', 'Mái nhà'])]),
  P('Cậu bé làm đèn kéo quân', 'Năm sáu tuổi, Bin thấy bà phải đứng lên ngồi xuống nhiều lần để bật tắt đèn. Bin nghĩ cách giúp bà. Cậu lấy một sợi dây dài buộc vào công tắc, đầu kia kéo tới cạnh giường. Thế là bà chỉ cần giật nhẹ sợi dây là đèn sáng. Cả nhà khen Bin là “nhà phát minh nhí”. Từ đó, Bin càng say mê tìm tòi. Cậu hiểu rằng phát minh bắt đầu từ việc quan sát và muốn giúp đỡ người khác.',
   [('Bin thấy bà gặp khó khăn gì?', 'Phải đứng lên ngồi xuống để bật tắt đèn', ['Không nhìn thấy chữ', 'Không nghe được tiếng']),
    ('Bin dùng vật gì để giúp bà?', 'Một sợi dây dài', ['Một chiếc gậy', 'Một cái điều khiển']),
    ('Bà chỉ cần làm gì là đèn sáng?', 'Giật nhẹ sợi dây', ['Vỗ tay hai cái', 'Gọi Bin đến']),
    ('Cả nhà gọi Bin là gì?', 'Nhà phát minh nhí', ['Nhà thơ nhí', 'Ca sĩ nhí']),
    ('Theo Bin, phát minh bắt đầu từ đâu?', 'Quan sát và muốn giúp đỡ người khác', ['Có thật nhiều tiền', 'Đọc thật nhiều truyện tranh'])])],
 AV=[('Từ nào có nghĩa là “tìm ra cái mới chưa ai làm”?', 'Phát minh', ['Bắt chước', 'Sao chép']),
     ('Người luôn tò mò, thích tìm hiểu thế giới xung quanh là người thế nào?', 'Ham hiểu biết', ['Thờ ơ', 'Lười biếng']),
     ('“Trải nghiệm” có nghĩa là gì?', 'Tự mình trải qua để hiểu biết', ['Nghe người khác kể lại', 'Đọc trong sách']),
     ('Cỏ cây “nói” với chúng ta bằng cách nào?', 'Bằng màu lá, tiếng xào xạc, hương thơm', ['Bằng giọng nói như người', 'Bằng chữ viết']),
     ('Khi viết bài tập làm văn, em cần làm gì?', 'Viết đúng sự thật, thể hiện suy nghĩ của mình', ['Chép bài của bạn', 'Viết thật dài dù không đúng']),
     ('Từ nào không cùng nhóm nghĩa với “khám phá”?', 'Bỏ qua', ['Tìm hiểu', 'Tìm tòi'])],
 W=dict(dt=['quả trứng', 'chiếc mỏ', 'công tắc', 'sợi dây', 'bầu trời', 'nhà phát minh'], dgt=['phá', 'mổ', 'buộc', 'giật', 'quan sát', 'tìm tòi'], tt=['nhọn hoắt', 'ngơ ngác', 'rộng lớn', 'bé tí', 'ướt', 'lấp lánh']),
 TC=[('Động từ nào chỉ hoạt động của chú gà con?', 'mổ', ['vàng', 'nhỏ xíu']),
     ('Động từ nào chỉ trạng thái?', 'yêu quý', ['mổ', 'buộc']),
     ('Trong câu “Chú gà con mổ vỏ trứng.”, động từ là:', 'mổ', ['gà con', 'vỏ trứng']),
     ('Từ nào thêm vào trước động từ để chỉ việc sắp diễn ra?', 'sẽ', ['đã', 'vừa']),
     ('Từ nào thêm vào trước động từ để chỉ việc đã xảy ra?', 'đã', ['sẽ', 'sắp']),
     ('Câu “Bin ___ buộc xong sợi dây.” nên điền từ nào?', 'đã', ['sẽ', 'đang']),
     ('Nhóm nào gồm toàn động từ?', 'đi, chạy, hát', ['bàn, ghế, tủ', 'xanh, đỏ, vàng'])],
 CT=[('phát minh', 'phác minh'), ('tò mò', 'tò mọ'), ('xào xạc', 'sào sạc'), ('giật dây', 'dật dây'), ('lông tơ', 'lông tơi'), ('nghiêng ngả', 'nghiêng ngã'), ('khám phá', 'khám phả')],
 CAU=[('', '', 'Chú gà con', 'phá vỏ chui ra.'), ('', '', 'Bin', 'buộc sợi dây vào công tắc.'), ('', '', 'Cả nhà', 'khen Bin là nhà phát minh nhí.'),
      ('', '', 'Bộ lông của chú gà', 'bông lên như tơ.'), ('', '', 'Lá cây', 'xào xạc trong gió.'), ('', '', 'Bà', 'giật nhẹ sợi dây.')],
 ORD=[['Chú gà con', 'kêu', 'chiếp chiếp.'], ['Bin', 'thích', 'tìm tòi', 'khám phá.'], ['Lá cây', 'rì rào', 'trong gió.'], ['Bà', 'khen', 'Bin', 'rất', 'thông minh.'], ['Em', 'quan sát', 'ổ trứng', 'cả buổi chiều.']],
 PUNCT=[('Làm sao chú gà chui ra được ☐', '?', None), ('Ôi, chú gà con đáng yêu quá ☐', '!', None), ('Bin buộc sợi dây vào công tắc ☐', '.', None), ('Bạn đã bao giờ phát minh ra thứ gì chưa ☐', '?', None), ('Chà, sáng kiến hay thật ☐', '!', None), ('Lá cây xào xạc trong gió ☐', '.', None)]))

U.append(dict(lab='Chặng 4', t='Con vẹt xanh · Chân trời cuối phố · Gặt chữ trên non · Trước ngày xa quê', vn='Bài 13 – 16 · Tập 1 · Trải nghiệm và khám phá',
 A=[P('Con vẹt biết chào', 'Ông nội tặng Tùng một chú vẹt xanh. Tùng dạy vẹt nói “Xin chào!”. Mấy ngày đầu, vẹt chỉ nghiêng đầu nhìn. Tùng kiên nhẫn nói đi nói lại. Một buổi sáng, khi Tùng vừa mở cửa, vẹt cất tiếng: “Xin chào! Xin chào!”. Tùng mừng quýnh, chạy đi khoe ông. Ông cười: “Dạy vẹt cũng như học bài, phải kiên nhẫn mới thành công.” Tùng gật đầu. Cậu biết mình vừa học thêm được một điều quý.',
   [('Ai tặng Tùng chú vẹt?', 'Ông nội', ['Bố', 'Cô giáo']),
    ('Tùng dạy vẹt nói câu gì?', 'Xin chào!', ['Tạm biệt!', 'Cảm ơn!']),
    ('Mấy ngày đầu, vẹt làm gì?', 'Chỉ nghiêng đầu nhìn', ['Nói liên tục', 'Bay đi mất']),
    ('Tùng đã dạy vẹt như thế nào?', 'Kiên nhẫn nói đi nói lại', ['Quát mắng vẹt', 'Bỏ đói vẹt']),
    ('Ông nói dạy vẹt giống việc gì?', 'Học bài', ['Nấu cơm', 'Đá bóng'])]),
  P('Mùa gặt trên núi', 'Nhà Pủa ở lưng chừng núi. Mùa lúa chín, cả bản vàng rực như dát nắng. Pủa theo mẹ lên nương gặt lúa. Mẹ cắt lúa nhanh thoăn thoắt, Pủa ôm từng bó lúa xếp vào gùi. Tối về, Pủa ngồi bên bếp lửa, giở vở ra đọc bài. Mẹ bảo: “Mẹ gặt lúa trên nương, con thì gặt chữ trên non. Chữ nuôi con khôn lớn như lúa nuôi cả nhà mình.” Pủa hứa sẽ học thật giỏi.',
   [('Nhà Pủa ở đâu?', 'Lưng chừng núi', ['Ven biển', 'Giữa thành phố']),
    ('Mùa lúa chín, bản trông như thế nào?', 'Vàng rực như dát nắng', ['Xanh mướt như ngọc', 'Trắng xoá như tuyết']),
    ('Pủa giúp mẹ việc gì?', 'Ôm lúa xếp vào gùi', ['Nấu cơm', 'Chăn trâu']),
    ('Mẹ nói con “gặt” gì?', 'Gặt chữ', ['Gặt ngô', 'Gặt hoa']),
    ('Pủa hứa điều gì?', 'Học thật giỏi', ['Đi chơi thật xa', 'Ngủ thật nhiều'])])],
 AV=[('“Chân trời” là gì?', 'Đường giới hạn nơi trời và đất như gặp nhau', ['Chân của bầu trời', 'Một con đường trong phố']),
     ('Nương là gì?', 'Đất trồng trọt trên đồi, núi', ['Ao nuôi cá', 'Vườn hoa trong phố']),
     ('Gùi là vật dùng để làm gì?', 'Đeo sau lưng để mang đồ', ['Đội lên đầu che nắng', 'Nấu cơm']),
     ('Từ nào đồng nghĩa với “kiên nhẫn”?', 'Nhẫn nại', ['Nóng vội', 'Bực bội']),
     ('Khi tra từ điển, các từ được sắp xếp theo thứ tự nào?', 'Thứ tự bảng chữ cái', ['Từ ngắn đến dài', 'Ngẫu nhiên']),
     ('Trước ngày xa quê, người ta thường có cảm xúc gì?', 'Bồi hồi, lưu luyến', ['Vô cảm', 'Tức giận'])],
 W=dict(dt=['con vẹt', 'nương lúa', 'bếp lửa', 'chiếc gùi', 'bản làng', 'chân trời'], dgt=['gặt', 'dạy', 'khoe', 'xếp', 'hứa', 'đeo'], tt=['vàng rực', 'thoăn thoắt', 'kiên nhẫn', 'mừng quýnh', 'xanh biếc', 'cao vút']),
 TC=[('Muốn biết nghĩa của một từ, em có thể dùng sách nào?', 'Từ điển', ['Truyện tranh', 'Sách bài tập Toán']),
     ('Trong từ điển, từ nào đứng trước?', 'bếp', ['gùi', 'nương']),
     ('Trong từ điển, từ nào đứng sau cùng?', 'vẹt', ['lúa', 'chữ']),
     ('Từ “gặt” trong “gặt chữ” được dùng với nghĩa nào?', 'Thu nhận được kiến thức', ['Cắt lúa ngoài đồng', 'Nhổ cỏ']),
     ('Trong câu “Tùng chạy đi khoe ông.”, các động từ là:', 'chạy, khoe', ['Tùng, ông', 'đi, ông']),
     ('Câu “Mẹ ___ gặt lúa trên nương.” (việc đang diễn ra) nên điền từ nào?', 'đang', ['đã', 'sẽ']),
     ('Từ nào là động từ chỉ hoạt động?', 'gặt', ['vui', 'buồn'])],
 CT=[('nương lúa', 'lương lúa'), ('lưng chừng', 'nưng chừng'), ('thoăn thoắt', 'thoăng thoắt'), ('chân trời', 'trân trời'), ('giở vở', 'dở vở'), ('bồi hồi', 'bồi hồ'), ('nghiêng đầu', 'nghiên đầu')],
 CAU=[('', '', 'Chú vẹt xanh', 'nghiêng đầu nhìn Tùng.'), ('', '', 'Mẹ', 'cắt lúa nhanh thoăn thoắt.'), ('', '', 'Cả bản', 'vàng rực như dát nắng.'),
      ('', '', 'Pủa', 'xếp từng bó lúa vào gùi.'), ('', '', 'Ông nội', 'tặng Tùng một chú vẹt.'), ('', '', 'Bếp lửa nhà Pủa', 'bập bùng suốt tối.')],
 ORD=[['Chú vẹt', 'cất tiếng', 'chào', 'Tùng.'], ['Mẹ', 'gặt lúa', 'trên', 'nương.'], ['Pủa', 'ngồi', 'đọc bài', 'bên bếp lửa.'], ['Tùng', 'mừng quýnh', 'chạy đi', 'khoe ông.'], ['Lúa', 'chín', 'vàng rực', 'cả bản.']],
 PUNCT=[('Con vẹt đã biết nói chưa ☐', '?', None), ('A, vẹt nói được rồi ☐', '!', None), ('Mẹ gặt lúa trên nương ☐', '.', None), ('Bao giờ lúa chín hả mẹ ☐', '?', None), ('Ôi, cánh đồng vàng rực ☐', '!', None), ('Pủa hứa sẽ học thật giỏi ☐', '.', None)]))
