from tv4a import P, U

# ===================== TẬP 1 · NIỀM VUI SÁNG TẠO =====================
U.append(dict(lab='Chặng 5', t='Vẽ màu · Đồng cỏ nở hoa · Thanh âm của núi · Bầu trời mùa thu', vn='Bài 17 – 20 · Tập 1 · Niềm vui sáng tạo',
 A=[P('Hộp màu của Thỏ', 'Thỏ con được mẹ tặng hộp bút màu mới. Thỏ tô màu xanh cho bầu trời, màu vàng cho ông mặt trời, màu hồng cho những đám mây buổi chiều. Bạn Sóc hỏi: “Sao mây của cậu lại màu hồng?”. Thỏ cười: “Vì lúc hoàng hôn, mây ửng hồng như má em bé đấy!”. Sóc ngẩn người rồi cũng xin vẽ cùng. Hai bạn vẽ cả một khu rừng rực rỡ sắc màu. Mẹ Thỏ khen: “Các con đã biết nhìn thế giới bằng đôi mắt của người hoạ sĩ.”',
   [('Mẹ tặng Thỏ món quà gì?', 'Hộp bút màu mới', ['Quyển truyện', 'Chiếc diều']),
    ('Thỏ tô màu gì cho bầu trời?', 'Màu xanh', ['Màu đỏ', 'Màu tím']),
    ('Vì sao Thỏ tô mây màu hồng?', 'Vì lúc hoàng hôn mây ửng hồng', ['Vì hết màu trắng', 'Vì Sóc bảo thế']),
    ('Hai bạn cùng nhau vẽ gì?', 'Một khu rừng rực rỡ sắc màu', ['Một ngôi nhà', 'Một con thuyền']),
    ('Mẹ Thỏ khen các con điều gì?', 'Biết nhìn thế giới bằng đôi mắt hoạ sĩ', ['Biết nấu ăn ngon', 'Biết chạy thật nhanh'])]),
  P('Tiếng núi', 'Buổi sáng trên núi, sương còn giăng trắng các sườn đồi. Tiếng suối róc rách chảy qua khe đá. Tiếng chim hót líu lo gọi nắng. Gió thổi qua rừng thông, reo lên vi vu như tiếng sáo. Xa xa, tiếng mõ trâu lốc cốc theo bước người đi nương. Bé Súa nghiêng tai nghe và thầm nghĩ: núi không im lặng chút nào, núi đang hát một bản nhạc thật dài, thật hay.',
   [('Buổi sáng, sương giăng ở đâu?', 'Các sườn đồi', ['Mặt biển', 'Mái nhà phố']),
    ('Tiếng suối được tả như thế nào?', 'Róc rách', ['Ầm ầm', 'Lộp độp']),
    ('Gió qua rừng thông reo như tiếng gì?', 'Tiếng sáo', ['Tiếng trống', 'Tiếng còi xe']),
    ('Tiếng lốc cốc là tiếng của vật gì?', 'Mõ trâu', ['Guốc gỗ', 'Mưa rơi']),
    ('Bé Súa nghĩ núi đang làm gì?', 'Hát một bản nhạc', ['Ngủ say', 'Khóc buồn'])])],
 AV=[('Từ nào chỉ âm thanh của suối?', 'róc rách', ['vi vu', 'líu lo']),
     ('Từ nào chỉ âm thanh của gió?', 'vi vu', ['róc rách', 'lộp độp']),
     ('Bầu trời mùa thu thường như thế nào?', 'Trong xanh, cao vời vợi', ['Âm u, mưa bão suốt ngày', 'Đỏ rực như lửa']),
     ('Người vẽ tranh chuyên nghiệp gọi là gì?', 'Hoạ sĩ', ['Nhạc sĩ', 'Kiến trúc sư']),
     ('Từ nào có nghĩa “nghĩ ra cái mới, cái hay”?', 'Sáng tạo', ['Bắt chước', 'Lặp lại']),
     ('“Hoàng hôn” là lúc nào?', 'Lúc mặt trời lặn', ['Lúc mặt trời mọc', 'Giữa trưa'])],
 W=dict(dt=['hộp màu', 'hoạ sĩ', 'sườn đồi', 'rừng thông', 'khe đá', 'hoàng hôn'], dgt=['tô', 'vẽ', 'thổi', 'chảy', 'reo', 'gọi'], tt=['rực rỡ', 'trong xanh', 'líu lo', 'ửng hồng', 'im lặng', 'cao vời vợi']),
 TC=[('Nhân hoá là gì?', 'Gọi, tả con vật, đồ vật… bằng từ ngữ dùng cho người', ['So sánh hai sự vật giống nhau', 'Lặp lại một từ nhiều lần']),
     ('Câu nào có dùng biện pháp nhân hoá?', 'Chị gió hát vi vu trên đồi.', ['Gió thổi mạnh trên đồi.', 'Trên đồi có nhiều gió.']),
     ('Trong câu “Ông mặt trời mỉm cười với em.”, sự vật nào được nhân hoá?', 'Mặt trời', ['Em', 'Nụ cười']),
     ('Từ nào dùng để nhân hoá con suối?', 'hát', ['chảy', 'trong']),
     ('Tính từ là gì?', 'Từ chỉ đặc điểm, tính chất của sự vật, hoạt động', ['Từ chỉ tên sự vật', 'Từ chỉ hoạt động']),
     ('Từ nào là tính từ chỉ màu sắc?', 'xanh biếc', ['bầu trời', 'bay']),
     ('Trong câu “Bầu trời mùa thu trong xanh.”, tính từ là:', 'trong xanh', ['bầu trời', 'mùa thu'])],
 CT=[('rực rỡ', 'rực rở'), ('sương mù', 'xương mù'), ('róc rách', 'rót rách'), ('líu lo', 'níu no'), ('ửng hồng', 'ửng hòng'), ('sáng tạo', 'xáng tạo'), ('vời vợi', 'vời vợ')],
 CAU=[('', '', 'Thỏ con', 'tô màu hồng cho đám mây.'), ('', '', 'Tiếng suối', 'róc rách qua khe đá.'), ('', '', 'Rừng thông', 'reo vi vu trong gió.'),
      ('', '', 'Bầu trời mùa thu', 'trong xanh, cao vời vợi.'), ('', '', 'Hai bạn nhỏ', 'vẽ một khu rừng rực rỡ.'), ('', '', 'Bé Súa', 'nghiêng tai nghe tiếng núi.')],
 ORD=[['Chị gió', 'hát', 'vi vu', 'trên đồi.'], ['Thỏ con', 'tô', 'bầu trời', 'màu xanh.'], ['Tiếng chim', 'líu lo', 'gọi', 'nắng.'], ['Bầu trời', 'mùa thu', 'thật', 'trong xanh.'], ['Ông mặt trời', 'mỉm cười', 'với', 'em.']],
 PUNCT=[('Sao mây của cậu lại màu hồng ☐', '?', None), ('Ôi, khu rừng rực rỡ quá ☐', '!', None), ('Tiếng suối róc rách qua khe đá ☐', '.', None), ('Bạn có nghe thấy tiếng núi hát không ☐', '?', None), ('Chà, bầu trời mùa thu đẹp thật ☐', '!', None), ('Thỏ tô màu vàng cho ông mặt trời ☐', '.', None)]))

U.append(dict(lab='Chặng 6', t='Làm thỏ con bằng giấy · Bức tường có nhiều phép lạ · Bét-tô-ven và bản xô-nát Ánh trăng · Người tìm đường lên các vì sao', vn='Bài 21 – 24 · Tập 1 · Niềm vui sáng tạo',
 A=[P('Bản nhạc dưới ánh trăng', 'Bét-tô-ven là nhà soạn nhạc nổi tiếng người Đức. Có một thời gian, ông gần như không còn nghe được gì nhưng vẫn say mê sáng tác. Người ta kể rằng, một đêm trăng, ông ghé vào một căn nhà nhỏ và đánh đàn cho một cô gái mù nghe. Tiếng đàn dịu dàng, lấp lánh như ánh trăng trên mặt hồ. Bản nhạc ấy về sau được gọi là xô-nát Ánh trăng. Đến nay, mọi người trên thế giới vẫn yêu thích tiếng đàn của ông.',
   [('Bét-tô-ven là ai?', 'Nhà soạn nhạc nổi tiếng người Đức', ['Hoạ sĩ người Pháp', 'Nhà thơ Việt Nam']),
    ('Bét-tô-ven gặp khó khăn gì?', 'Gần như không nghe được gì', ['Không nhìn thấy gì', 'Không đi lại được']),
    ('Ông đánh đàn cho ai nghe?', 'Một cô gái mù', ['Nhà vua', 'Các học trò']),
    ('Tiếng đàn được so sánh với gì?', 'Ánh trăng trên mặt hồ', ['Tiếng sấm', 'Ngọn lửa']),
    ('Câu chuyện cho thấy Bét-tô-ven là người thế nào?', 'Say mê sáng tác, vượt qua khó khăn', ['Dễ bỏ cuộc', 'Không thích âm nhạc'])]),
  P('Ước mơ bay vào vũ trụ', 'Hồi nhỏ, Xi-ôn-cốp-xki rất ước mơ được bay lên bầu trời. Có lần, cậu trèo lên mái nhà, cầm theo chiếc ô rồi nhảy xuống để thử bay như chim. Cậu bị ngã rất đau. Từ đó, cậu miệt mài đọc sách, làm thí nghiệm suốt nhiều năm. Ông đã nghiên cứu về tên lửa và mở đường cho con người bay vào vũ trụ. Ông từng nói: “Các vì sao không phải để tặng cho kẻ lười biếng.”',
   [('Hồi nhỏ, Xi-ôn-cốp-xki ước mơ điều gì?', 'Được bay lên bầu trời', ['Được làm vua', 'Được đi tàu ngầm']),
    ('Cậu đã thử bay bằng cách nào?', 'Cầm ô nhảy từ mái nhà xuống', ['Buộc cánh vào tay', 'Đi khinh khí cầu']),
    ('Sau khi bị ngã, cậu đã làm gì?', 'Miệt mài đọc sách, làm thí nghiệm', ['Bỏ ước mơ', 'Chỉ đi chơi']),
    ('Ông nghiên cứu về điều gì?', 'Tên lửa', ['Thuốc chữa bệnh', 'Nhạc cụ']),
    ('Câu nói của ông khuyên chúng ta điều gì?', 'Phải chăm chỉ mới đạt được ước mơ', ['Không nên mơ ước', 'Chỉ cần may mắn'])])],
 AV=[('“Bức tường có nhiều phép lạ” là bức tường thế nào?', 'Được vẽ tranh đẹp làm thay đổi cả không gian', ['Biết nói chuyện', 'Tự di chuyển']),
     ('Xô-nát là gì?', 'Một loại bản nhạc', ['Một loại bánh', 'Một loài hoa']),
     ('Từ nào đồng nghĩa với “miệt mài”?', 'Chăm chú', ['Hời hợt', 'Lơ đãng']),
     ('Để làm thỏ con bằng giấy, em cần những gì?', 'Giấy màu, kéo, hồ dán', ['Đất sét, lò nung', 'Gỗ, cưa, đinh']),
     ('Từ nào chỉ người nghiên cứu khoa học?', 'Nhà khoa học', ['Nhà văn', 'Ca sĩ']),
     ('Câu tục ngữ nào khuyên kiên trì?', 'Có công mài sắt, có ngày nên kim', ['Ăn quả nhớ kẻ trồng cây', 'Lá lành đùm lá rách'])],
 W=dict(dt=['nhà soạn nhạc', 'tên lửa', 'vũ trụ', 'mái nhà', 'tờ giấy', 'bức tường'], dgt=['sáng tác', 'nghiên cứu', 'trèo', 'gấp', 'cắt', 'dán'], tt=['dịu dàng', 'nổi tiếng', 'lười biếng', 'lấp lánh', 'miệt mài', 'khéo léo']),
 TC=[('Tính từ nào chỉ mức độ cao nhất?', 'đẹp nhất', ['hơi đẹp', 'đẹp']),
     ('Từ nào thêm vào để tính từ “xanh” chỉ mức độ cao?', 'rất', ['hơi', 'khá']),
     ('Trong câu “Tiếng đàn dịu dàng, lấp lánh.”, các tính từ là:', 'dịu dàng, lấp lánh', ['tiếng, đàn', 'tiếng đàn, dịu dàng']),
     ('Câu nào có dùng nhân hoá?', 'Những ngôi sao nháy mắt với em.', ['Những ngôi sao lấp lánh.', 'Trời có nhiều sao.']),
     ('Nhóm từ nào gồm toàn tính từ?', 'cao, thấp, xanh, đỏ', ['đi, cao, bàn, xanh', 'vẽ, hát, múa, đẹp']),
     ('Từ nào là tính từ chỉ tính nết?', 'chăm chỉ', ['bàn ghế', 'trèo']),
     ('“Đỏ chót” là tính từ chỉ đặc điểm gì?', 'Màu sắc', ['Hình dáng', 'Âm thanh'])],
 CT=[('Bét-tô-ven', 'Bét tô ven'), ('Xi-ôn-cốp-xki', 'Xi ôn cốp xki'), ('xô-nát', 'sô-nát'), ('nghiên cứu', 'nghiêng cứu'), ('tên lửa', 'tên nửa'), ('miệt mài', 'miệc mài'), ('trèo cây', 'chèo cây')],
 CAU=[('', '', 'Bét-tô-ven', 'là nhà soạn nhạc nổi tiếng.'), ('', '', 'Tiếng đàn của ông', 'dịu dàng như ánh trăng.'), ('', '', 'Xi-ôn-cốp-xki', 'nghiên cứu về tên lửa.'),
      ('', '', 'Chú thỏ bằng giấy', 'trông rất ngộ nghĩnh.'), ('', '', 'Bức tường cũ', 'bỗng rực rỡ sắc màu.'), ('', '', 'Các bạn nhỏ', 'gấp thỏ con bằng giấy màu.')],
 ORD=[['Các vì sao', 'nháy mắt', 'với', 'em.'], ['Em', 'gấp', 'một', 'chú thỏ', 'bằng giấy.'], ['Tiếng đàn', 'dịu dàng', 'như', 'ánh trăng.'], ['Ông', 'miệt mài', 'làm', 'thí nghiệm.'], ['Bức tường', 'bỗng', 'rực rỡ', 'sắc màu.']],
 PUNCT=[('Ôi, chú thỏ giấy ngộ nghĩnh quá ☐', '!', None), ('Bạn đã nghe bản xô-nát Ánh trăng chưa ☐', '?', None), ('Ông nghiên cứu về tên lửa ☐', '.', None), ('Làm sao để gấp được chú thỏ ☐', '?', None), ('Chà, bức tường đẹp thật ☐', '!', None), ('Bét-tô-ven say mê sáng tác ☐', '.', None)]))

# ===================== TẬP 1 · CHẮP CÁNH ƯỚC MƠ =====================
U.append(dict(lab='Chặng 7', t='Bay cùng ước mơ · Con trai người làm vườn · Nếu em có một khu vườn · Bốn mùa mơ ước', vn='Bài 25 – 28 · Tập 1 · Chắp cánh ước mơ',
 A=[P('Chiếc máy bay giấy', 'Chiều nào, Hải cũng ra đầu ngõ thả máy bay giấy. Chiếc máy bay trắng muốt lượn một vòng rồi đáp nhẹ xuống bãi cỏ. Hải ước mơ sau này trở thành phi công, lái những chiếc máy bay thật đưa mọi người đi khắp nơi. Bố bảo: “Muốn làm phi công, con phải học giỏi và rèn luyện sức khoẻ.” Từ hôm ấy, sáng nào Hải cũng dậy sớm chạy bộ cùng bố. Ước mơ của Hải như chiếc máy bay đang từ từ cất cánh.',
   [('Chiều nào Hải cũng làm gì?', 'Thả máy bay giấy', ['Thả diều', 'Đá bóng']),
    ('Hải ước mơ trở thành ai?', 'Phi công', ['Bác sĩ', 'Thầy giáo']),
    ('Bố khuyên Hải điều gì?', 'Học giỏi và rèn luyện sức khoẻ', ['Chỉ cần gấp nhiều máy bay', 'Không nên mơ ước']),
    ('Sáng nào Hải cũng làm gì?', 'Dậy sớm chạy bộ cùng bố', ['Ngủ đến trưa', 'Xem hoạt hình']),
    ('Ước mơ của Hải được so sánh với gì?', 'Chiếc máy bay đang cất cánh', ['Con thuyền đang chìm', 'Ngôi sao đã tắt'])]),
  P('Khu vườn mơ ước', 'Nếu có một khu vườn, em sẽ trồng thật nhiều loại cây. Góc này là luống rau cải xanh non cho bữa cơm của mẹ. Góc kia là những khóm hoa hồng, hoa cúc để bà ngắm mỗi sáng. Giữa vườn, em trồng một cây xoài để mùa hè cả nhà ngồi dưới bóng mát. Em sẽ làm một chiếc chòi nhỏ cho chim về làm tổ. Khu vườn ấy sẽ đầy tiếng chim và hương hoa, là món quà em tặng cả gia đình.',
   [('Luống rau cải để làm gì?', 'Cho bữa cơm của mẹ', ['Để bán lấy tiền', 'Cho gà ăn']),
    ('Khóm hoa để ai ngắm mỗi sáng?', 'Bà', ['Ông', 'Em bé']),
    ('Giữa vườn, bạn nhỏ trồng cây gì?', 'Cây xoài', ['Cây bàng', 'Cây dừa']),
    ('Chiếc chòi nhỏ làm cho ai?', 'Chim về làm tổ', ['Mèo con ngủ', 'Chó con chơi']),
    ('Khu vườn là món quà tặng ai?', 'Cả gia đình', ['Cô giáo', 'Bạn thân'])])],
 AV=[('Từ nào cùng nghĩa với “ước mơ”?', 'Mơ ước', ['Thất vọng', 'Lo lắng']),
     ('Ước mơ nào đáng được khuyến khích?', 'Trở thành bác sĩ chữa bệnh cho mọi người', ['Không phải học bài', 'Có thật nhiều đồ chơi để khoe']),
     ('Từ nào chỉ ước mơ lớn, cao đẹp?', 'Hoài bão', ['Mơ mộng', 'Viển vông']),
     ('Câu tục ngữ “Cầu được ước thấy” nói về điều gì?', 'Điều mong muốn đã thành hiện thực', ['Việc đi qua cầu', 'Việc nhìn thấy cây cầu']),
     ('Người chăm sóc vườn cây gọi là gì?', 'Người làm vườn', ['Người lái đò', 'Người thợ mỏ']),
     ('Bốn mùa trong năm gồm những mùa nào?', 'Xuân, hạ, thu, đông', ['Mưa, nắng, gió, bão', 'Sáng, trưa, chiều, tối'])],
 W=dict(dt=['phi công', 'khu vườn', 'luống rau', 'chiếc chòi', 'bóng mát', 'bãi cỏ'], dgt=['thả', 'lượn', 'cất cánh', 'trồng', 'ngắm', 'làm tổ'], tt=['trắng muốt', 'xanh non', 'khoẻ mạnh', 'mát rượi', 'thơm ngát', 'nhỏ xinh']),
 TC=[('Dấu gạch ngang (–) dùng để làm gì?', 'Đánh dấu lời nói của nhân vật, các ý liệt kê', ['Kết thúc câu hỏi', 'Bộc lộ cảm xúc']),
     ('Trong đoạn hội thoại, dấu gạch ngang đặt ở đâu?', 'Đầu lời nói của nhân vật', ['Cuối mỗi câu', 'Giữa hai tiếng']),
     ('Câu nào dùng dấu gạch ngang đúng?', '– Con muốn làm phi công! – Hải nói.', ['Con muốn – làm phi công.', 'Con muốn làm – phi công!']),
     ('Dấu gạch ngang trong câu “– Con muốn làm phi công!” đánh dấu điều gì?', 'Lời nói của nhân vật', ['Phần chú thích', 'Các ý liệt kê']),
     ('Câu “Ước gì em được bay lên trời!” bộc lộ điều gì?', 'Mong ước của em', ['Một câu hỏi', 'Lời chào hỏi']),
     ('Danh từ nào chỉ người làm nghề lái máy bay?', 'phi công', ['bay lượn', 'cao vút'])],
 CT=[('chòi nhỏ', 'tròi nhỏ'), ('ước mơ', 'ướt mơ'), ('xanh non', 'xanh lon'), ('cất cánh', 'cấc cánh'), ('hoài bão', 'hoài bảo'), ('rèn luyện', 'dèn luyện'), ('trắng muốt', 'chắng muốt')],
 CAU=[('', '', 'Chiếc máy bay giấy', 'lượn một vòng trên bãi cỏ.'), ('', '', 'Hải', 'ước mơ trở thành phi công.'), ('', '', 'Khu vườn', 'đầy tiếng chim và hương hoa.'),
      ('', '', 'Bà', 'ngắm hoa mỗi sáng.'), ('', '', 'Cây xoài giữa vườn', 'toả bóng mát.'), ('', '', 'Bố', 'chạy bộ cùng Hải mỗi sáng.')],
 ORD=[['Hải', 'ước mơ', 'trở thành', 'phi công.'], ['Em', 'trồng', 'rau cải', 'cho mẹ.'], ['Chim', 'về', 'làm tổ', 'trong vườn.'], ['Chiếc máy bay', 'từ từ', 'cất cánh.'], ['Khu vườn', 'thơm ngát', 'hương hoa.']],
 PUNCT=[('Hải hỏi bố ☐ “Con có thể làm phi công không ạ?”', ':', [':', '.', '?']), ('Khu vườn có đủ loại cây ☐ xoài, bưởi, cam, chanh.', ':', [':', '?', '!']),
        ('☐ Con muốn làm phi công! – Hải nói.', '–', ['–', '?', '!']), ('Ôi, khu vườn đẹp quá ☐', '!', None), ('Bạn mơ ước làm nghề gì ☐', '?', None), ('Em sẽ trồng một cây xoài giữa vườn ☐', '.', None)]))

U.append(dict(lab='Chặng 8', t='Ở Vương quốc Tương Lai · Cánh chim nhỏ · Nếu chúng mình có phép lạ · Anh Ba', vn='Bài 29 – 32 · Tập 1 · Chắp cánh ước mơ',
 A=[P('Chuyến thăm thành phố tương lai', 'Trong giấc mơ, Tin đến thăm một thành phố của tương lai. Ở đó, những chiếc xe chạy bằng năng lượng mặt trời lặng lẽ lướt trên đường, không một chút khói bụi. Các toà nhà phủ đầy cây xanh như những khu vườn treo. Rô-bốt giúp mọi người dọn dẹp, tưới cây. Một bạn nhỏ ở đó nói: “Những điều này đều do trẻ em sáng chế ra đấy!”. Tin tỉnh dậy, mỉm cười và tự nhủ phải học thật giỏi để góp phần làm nên tương lai tươi đẹp.',
   [('Tin đến thăm thành phố tương lai khi nào?', 'Trong giấc mơ', ['Trong kì nghỉ hè', 'Trong chuyến dã ngoại']),
    ('Xe ở thành phố tương lai chạy bằng gì?', 'Năng lượng mặt trời', ['Than đá', 'Sức kéo của ngựa']),
    ('Các toà nhà trông như thế nào?', 'Phủ đầy cây xanh', ['Xám xịt, cũ kĩ', 'Toàn bằng băng đá']),
    ('Rô-bốt giúp mọi người việc gì?', 'Dọn dẹp, tưới cây', ['Làm bài tập hộ', 'Đi học thay']),
    ('Tin tự nhủ điều gì?', 'Học thật giỏi để góp phần làm nên tương lai', ['Ngủ thật nhiều để mơ tiếp', 'Không cần học nữa'])]),
  P('Anh Ba sửa cầu', 'Anh Ba là người thợ mộc hiền lành trong xóm. Cây cầu tre bắc qua con mương đã cũ, mỗi lần các em nhỏ đi học qua đều run run. Không đợi ai nhờ, anh Ba vác tre, mang dao, cưa ra sửa cầu. Anh làm suốt hai ngày, mồ hôi ướt đẫm lưng áo. Cây cầu mới chắc chắn, có cả tay vịn. Các em nhỏ reo lên: “Cảm ơn anh Ba!”. Anh chỉ cười hiền: “Các em đi học an toàn là anh vui rồi.”',
   [('Anh Ba làm nghề gì?', 'Thợ mộc', ['Thợ may', 'Bác sĩ']),
    ('Vì sao các em nhỏ qua cầu thấy run?', 'Vì cây cầu tre đã cũ', ['Vì trời lạnh', 'Vì có chó dữ']),
    ('Anh Ba sửa cầu trong bao lâu?', 'Hai ngày', ['Một tuần', 'Một buổi sáng']),
    ('Cây cầu mới có gì đặc biệt?', 'Chắc chắn, có tay vịn', ['Được sơn màu đỏ', 'Làm bằng sắt']),
    ('Điều gì làm anh Ba vui?', 'Các em đi học an toàn', ['Được trả nhiều tiền', 'Được khen trên báo'])])],
 AV=[('“Phép lạ” là gì?', 'Điều kì diệu khác thường', ['Một phép tính khó', 'Một lá thư']),
     ('Từ nào chỉ thời gian sắp tới?', 'Tương lai', ['Quá khứ', 'Ngày xưa']),
     ('Người làm các đồ vật bằng gỗ gọi là gì?', 'Thợ mộc', ['Thợ rèn', 'Thợ xây']),
     ('Việc làm của anh Ba thể hiện đức tính gì?', 'Tốt bụng, vì mọi người', ['Ích kỉ', 'Lười biếng']),
     ('Ước mơ nào là ước mơ viển vông?', 'Muốn không phải làm gì mà vẫn giỏi', ['Muốn chữa bệnh cho người nghèo', 'Muốn trồng thật nhiều cây xanh']),
     ('Từ nào đồng nghĩa với “sáng chế”?', 'Phát minh', ['Bắt chước', 'Phá hỏng'])],
 W=dict(dt=['tương lai', 'rô-bốt', 'năng lượng', 'thợ mộc', 'cây cầu', 'con mương'], dgt=['lướt', 'sáng chế', 'tưới', 'vác', 'sửa', 'reo'], tt=['tươi đẹp', 'hiền lành', 'chắc chắn', 'an toàn', 'ướt đẫm', 'kì diệu']),
 TC=[('Trong câu “Anh Ba vác tre ra sửa cầu.”, danh từ là:', 'Anh Ba, tre, cầu', ['vác, sửa', 'ra, sửa']),
     ('Trong câu “Các em nhỏ reo lên vui sướng.”, động từ là:', 'reo', ['em nhỏ', 'vui sướng']),
     ('Trong câu “Cây cầu mới rất chắc chắn.”, tính từ là:', 'chắc chắn', ['cây cầu', 'rất']),
     ('Dấu gạch ngang trong câu “Các bạn nhớ mang: – bút; – thước; – vở.” dùng để làm gì?', 'Đánh dấu các ý liệt kê', ['Đánh dấu lời nói', 'Kết thúc câu']),
     ('Dấu gạch ngang còn dùng để làm gì?', 'Nối các từ ngữ trong một liên danh (tuyến đường Hà Nội – Hải Phòng)', ['Thay dấu chấm hỏi', 'Tách các tiếng trong từ']),
     ('Từ nào không phải danh từ?', 'sáng chế', ['rô-bốt', 'tương lai'])],
 CT=[('rô-bốt', 'rô bốt'), ('sáng chế', 'sáng trế'), ('lướt nhẹ', 'lước nhẹ'), ('lặng lẽ', 'lặn lẽ'), ('xóm nhỏ', 'sóm nhỏ'), ('tay vịn', 'tay vịnh'), ('mồ hôi', 'mồ hoi')],
 CAU=[('', '', 'Những chiếc xe', 'lặng lẽ lướt trên đường.'), ('', '', 'Anh Ba', 'là thợ mộc hiền lành.'), ('', '', 'Rô-bốt', 'giúp mọi người tưới cây.'),
      ('', '', 'Cây cầu mới', 'rất chắc chắn.'), ('', '', 'Các em nhỏ', 'reo lên vui sướng.'), ('', '', 'Thành phố tương lai', 'phủ đầy cây xanh.')],
 ORD=[['Anh Ba', 'sửa', 'cây cầu', 'tre.'], ['Rô-bốt', 'giúp', 'mọi người', 'dọn dẹp.'], ['Tin', 'mơ', 'thấy', 'thành phố', 'tương lai.'], ['Các em', 'đi học', 'an toàn.'], ['Xe', 'chạy', 'bằng', 'năng lượng mặt trời.']],
 PUNCT=[('Các em nhỏ reo lên ☐ “Cảm ơn anh Ba!”', ':', [':', '.', '?']), ('☐ Các em đi học an toàn là anh vui rồi.', '–', ['–', '!', '?']),
        ('Chuyến tàu Hà Nội ☐ Huế khởi hành lúc 7 giờ.', '–', ['–', '?', '!']), ('Bạn có muốn đến thăm thành phố tương lai không ☐', '?', None), ('Chà, rô-bốt giỏi quá ☐', '!', None), ('Anh Ba sửa cầu suốt hai ngày ☐', '.', None)]))
