from tv4b import P, U

# ===================== TẬP 2 · SỐNG ĐỂ YÊU THƯƠNG =====================
U.append(dict(lab='Chặng 9', t='Hải Thượng Lãn Ông · Vệt phấn trên mặt bàn · Ông Bụt đã đến · Quả ngọt cuối mùa', vn='Bài 1 – 4 · Tập 2 · Sống để yêu thương',
 A=[P('Người thầy thuốc nhân hậu', 'Hải Thượng Lãn Ông tên thật là Lê Hữu Trác, một danh y nổi tiếng của nước ta ở thế kỉ XVIII. Ông không màng danh lợi, chỉ chuyên tâm chữa bệnh cứu người. Nhà nghèo nào có người ốm, ông đều tận tình thăm khám, nhiều khi còn cho thêm gạo, củi. Ông để lại cho đời sau những bộ sách thuốc quý. Tấm lòng thương người của ông mãi được nhân dân kính trọng.',
   [('Tên thật của Hải Thượng Lãn Ông là gì?', 'Lê Hữu Trác', ['Tuệ Tĩnh', 'Nguyễn Trãi']),
    ('Ông sống vào thế kỉ nào?', 'Thế kỉ XVIII', ['Thế kỉ XX', 'Thế kỉ X']),
    ('Ông chuyên tâm vào việc gì?', 'Chữa bệnh cứu người', ['Buôn bán thuốc', 'Làm quan']),
    ('Với người nghèo, ông còn làm gì?', 'Cho thêm gạo, củi', ['Lấy thêm tiền', 'Từ chối chữa bệnh']),
    ('Ông để lại cho đời sau điều gì?', 'Những bộ sách thuốc quý', ['Một lâu đài', 'Nhiều vàng bạc'])]),
  P('Vệt phấn trên bàn', 'Giờ ra chơi, Nam lỡ tay làm gãy chiếc thước của bạn Lan. Nam sợ bị trách nên im lặng. Lan buồn lắm nhưng không nói gì. Cuối buổi, trên mặt bàn của Lan có một vệt phấn trắng viết nắn nót: “Tớ xin lỗi. Mai tớ sẽ đền cậu chiếc thước mới. – Nam”. Lan mỉm cười, lấy phấn viết bên cạnh: “Không sao đâu. Mình vẫn là bạn tốt!”. Hôm sau, hai bạn cùng nhau đi học, vui vẻ như chưa có chuyện gì.',
   [('Nam đã làm gì với chiếc thước của Lan?', 'Làm gãy', ['Làm mất', 'Tô màu']),
    ('Vì sao lúc đầu Nam im lặng?', 'Vì sợ bị trách', ['Vì không biết', 'Vì đang ốm']),
    ('Nam đã xin lỗi Lan bằng cách nào?', 'Viết lời xin lỗi bằng phấn trên mặt bàn', ['Nhờ cô giáo nói hộ', 'Gọi điện thoại']),
    ('Lan trả lời Nam thế nào?', 'Không sao đâu. Mình vẫn là bạn tốt!', ['Tớ sẽ mách cô giáo!', 'Tớ không chơi với cậu nữa!']),
    ('Câu chuyện khuyên em điều gì?', 'Biết nhận lỗi và biết tha thứ', ['Làm hỏng đồ thì nên giấu đi', 'Không cho bạn mượn đồ'])])],
 AV=[('“Danh y” là gì?', 'Thầy thuốc giỏi, nổi tiếng', ['Người bán thuốc', 'Cuốn sách thuốc']),
     ('Từ nào cùng nghĩa với “nhân hậu”?', 'Nhân từ', ['Độc ác', 'Hung dữ']),
     ('Câu tục ngữ nào nói về lòng thương người?', 'Lá lành đùm lá rách', ['Nước chảy đá mòn', 'Có chí thì nên']),
     ('Trong truyện cổ, ông Bụt thường làm gì?', 'Hiện ra giúp đỡ người hiền lành', ['Bắt nạt người nghèo', 'Canh giữ kho báu']),
     ('“Quả ngọt cuối mùa” trong bài thơ là quả bà dành cho ai?', 'Con cháu ở xa', ['Hàng xóm', 'Người bán hàng']),
     ('Từ nào trái nghĩa với “yêu thương”?', 'Ghét bỏ', ['Quý mến', 'Thương yêu'])],
 W=dict(dt=['danh y', 'sách thuốc', 'viên phấn', 'mặt bàn', 'lời xin lỗi', 'tấm lòng'], dgt=['chữa bệnh', 'thăm khám', 'xin lỗi', 'tha thứ', 'đền', 'mỉm cười'], tt=['nhân hậu', 'tận tình', 'nắn nót', 'vui vẻ', 'quý giá', 'ân cần']),
 TC=[('Câu có mấy thành phần chính?', 'Hai: chủ ngữ và vị ngữ', ['Một: chủ ngữ', 'Ba: chủ ngữ, vị ngữ, trạng ngữ']),
     ('Chủ ngữ trả lời cho câu hỏi nào?', 'Ai? Cái gì? Con gì?', ['Làm gì? Thế nào?', 'Ở đâu? Khi nào?']),
     ('Vị ngữ trả lời cho câu hỏi nào?', 'Làm gì? Thế nào? Là gì?', ['Ai? Cái gì?', 'Vì sao?']),
     ('Câu nào là câu hoàn chỉnh?', 'Lan mỉm cười.', ['Chiếc thước của Lan.', 'Trên mặt bàn.']),
     ('Tập hợp từ nào chưa thành câu?', 'Những bộ sách thuốc quý', ['Ông chữa bệnh cho người nghèo.', 'Nam xin lỗi Lan.']),
     ('Câu “Ai viết lên mặt bàn?” dùng để làm gì?', 'Hỏi', ['Kể', 'Bộc lộ cảm xúc'])],
 CT=[('chữa bệnh', 'chửa bệnh'), ('danh y', 'dang y'), ('xin lỗi', 'sin lỗi'), ('nắn nót', 'lắn nót'), ('tha thứ', 'tha thứa'), ('thăm khám', 'thăm kháng'), ('trách mắng', 'chách mắng')],
 CAU=[('', '', 'Hải Thượng Lãn Ông', 'là một danh y nổi tiếng.'), ('', '', 'Ông', 'tận tình chữa bệnh cho người nghèo.'), ('', '', 'Nam', 'viết lời xin lỗi lên mặt bàn.'),
      ('', '', 'Lan', 'mỉm cười tha thứ cho bạn.'), ('', '', 'Quả ngọt cuối mùa', 'bà để dành cho cháu.'), ('Giờ ra chơi', 'tg', 'Nam', 'lỡ tay làm gãy thước của Lan.')],
 ORD=[['Ông', 'chữa bệnh', 'cho', 'người nghèo.'], ['Nam', 'xin lỗi', 'Lan', 'bằng', 'vệt phấn.'], ['Lan', 'tha thứ', 'cho', 'bạn.'], ['Bà', 'để dành', 'quả ngọt', 'cho cháu.'], ['Ông Bụt', 'hiện ra', 'giúp', 'cô bé.']],
 PUNCT=[('Nam viết ☐ “Tớ xin lỗi.”', ':', [':', '?', '!']), ('Cậu có giận tớ không ☐', '?', None), ('Ôi, bạn tốt quá ☐', '!', None), ('Hải Thượng Lãn Ông là một danh y ☐', '.', None), ('Lan trả lời ☐ “Không sao đâu.”', ':', [':', '?', '.']), ('Ai đã viết lên mặt bàn ☐', '?', None)]))

U.append(dict(lab='Chặng 10', t='Tờ báo tường của tôi · Tiếng ru · Con muốn làm một cái cây · Trên khóm tre đầu ngõ', vn='Bài 5 – 8 · Tập 2 · Sống để yêu thương',
 A=[P('Tờ báo tường lớp em', 'Để chào mừng ngày Nhà giáo Việt Nam 20 – 11, lớp em làm một tờ báo tường. Bạn Hùng viết một bài thơ về cô giáo. Bạn Thu vẽ bức tranh bó hoa thật to. Tổ em sưu tầm những câu chuyện hay về thầy cô. Ai cũng góp một tay, người cắt, người dán, người trang trí. Khi tờ báo hoàn thành, cả lớp reo lên thích thú. Cô giáo xúc động nói: “Đây là món quà ý nghĩa nhất cô nhận được.”',
   [('Lớp em làm báo tường để chào mừng ngày nào?', 'Ngày Nhà giáo Việt Nam 20 – 11', ['Ngày Quốc tế Thiếu nhi 1 – 6', 'Tết Trung thu']),
    ('Bạn Hùng góp gì cho tờ báo?', 'Một bài thơ về cô giáo', ['Một bức tranh', 'Một câu đố']),
    ('Bạn Thu vẽ gì?', 'Bó hoa thật to', ['Ngôi trường', 'Con thuyền']),
    ('Các bạn làm báo tường như thế nào?', 'Ai cũng góp một tay', ['Chỉ một bạn làm', 'Nhờ bố mẹ làm hộ']),
    ('Cô giáo cảm thấy thế nào?', 'Xúc động', ['Bực bội', 'Lo lắng'])]),
  P('Khóm tre đầu ngõ', 'Đầu ngõ nhà em có một khóm tre xanh. Sáng sớm, chim chào mào, chim sẻ ríu rít gọi nhau trên cành. Trưa hè, bóng tre mát rượi, các cụ già ngồi hóng gió, bọn trẻ chơi ô ăn quan. Chiều về, gió thổi, lá tre xào xạc như tiếng ai thì thầm. Khóm tre đứng đó bao năm, lặng lẽ che chở cho cả xóm. Em yêu khóm tre như yêu một người bạn thân thiết.',
   [('Khóm tre ở đâu?', 'Đầu ngõ nhà em', ['Giữa cánh đồng', 'Trong sân trường']),
    ('Buổi sáng, trên cành tre có gì?', 'Chim ríu rít gọi nhau', ['Ve kêu râm ran', 'Mèo nằm ngủ']),
    ('Trưa hè, bọn trẻ chơi trò gì dưới bóng tre?', 'Ô ăn quan', ['Thả diều', 'Đá cầu']),
    ('Lá tre xào xạc được ví như gì?', 'Tiếng ai thì thầm', ['Tiếng sấm rền', 'Tiếng còi tàu']),
    ('Bạn nhỏ yêu khóm tre như yêu ai?', 'Một người bạn thân thiết', ['Một người lạ', 'Một vị khách'])])],
 AV=[('“Báo tường” là gì?', 'Tờ báo do tập thể làm, dán trên tường', ['Tờ báo in hằng ngày', 'Bức tường có chữ']),
     ('Lời ru của mẹ thường gửi gắm điều gì?', 'Tình yêu thương, lời dạy dỗ', ['Lời trách mắng', 'Tin tức thời sự']),
     ('Câu “Muốn làm một cái cây” thể hiện mong muốn gì?', 'Được che chở, mang lại điều tốt cho mọi người', ['Được đứng yên không làm gì', 'Được cao hơn mọi người']),
     ('Từ nào chỉ sự gắn bó, giúp đỡ nhau?', 'Đoàn kết', ['Chia rẽ', 'Ganh tị']),
     ('Câu tục ngữ “Một cây làm chẳng nên non, ba cây chụm lại nên hòn núi cao” khuyên gì?', 'Đoàn kết tạo nên sức mạnh', ['Nên trồng nhiều cây', 'Leo núi rất khó']),
     ('Từ nào là từ chỉ tình cảm gia đình?', 'Hiếu thảo', ['Dũng cảm', 'Nhanh nhẹn'])],
 W=dict(dt=['báo tường', 'bài thơ', 'khóm tre', 'chim chào mào', 'lời ru', 'ngõ nhỏ'], dgt=['sưu tầm', 'trang trí', 'che chở', 'hóng', 'ru', 'thì thầm'], tt=['xúc động', 'mát rượi', 'thân thiết', 'ý nghĩa', 'ríu rít', 'ngọt ngào']),
 TC=[('Chủ ngữ của câu thường do từ loại nào tạo thành?', 'Danh từ (cụm danh từ)', ['Tính từ', 'Dấu câu']),
     ('Vị ngữ của câu “Khóm tre xanh mát.” là:', 'xanh mát', ['Khóm tre', 'Khóm']),
     ('Chủ ngữ của câu “Cả lớp reo lên thích thú.” là:', 'Cả lớp', ['reo lên', 'thích thú']),
     ('Câu nào có vị ngữ trả lời câu hỏi “Là gì?”', 'Hùng là cây bút của lớp.', ['Hùng viết thơ.', 'Hùng rất vui.']),
     ('Câu nào có vị ngữ nêu đặc điểm (trả lời câu hỏi “Thế nào?”)?', 'Bóng tre mát rượi.', ['Bọn trẻ chơi ô ăn quan.', 'Tre là bạn của em.']),
     ('Từ nào có thể làm chủ ngữ trong câu “… ríu rít trên cành.”?', 'Đàn chim', ['Bay nhảy', 'Xanh tươi'])],
 CT=[('sưu tầm', 'xưu tầm'), ('trang trí', 'chang trí'), ('xúc động', 'súc động'), ('ríu rít', 'díu dít'), ('che chở', 'tre chở'), ('ô ăn quan', 'ô ăn quang'), ('thì thầm', 'thì thằm')],
 CAU=[('', '', 'Bạn Hùng', 'viết một bài thơ về cô giáo.'), ('', '', 'Tờ báo tường', 'rất đẹp và ý nghĩa.'), ('', '', 'Khóm tre đầu ngõ', 'xanh mát quanh năm.'),
      ('Sáng sớm', 'tg', 'chim chào mào', 'ríu rít trên cành.'), ('Trưa hè', 'tg', 'các cụ già', 'ngồi hóng gió dưới bóng tre.'), ('', '', 'Lời ru của mẹ', 'ngọt ngào, êm ái.')],
 ORD=[['Cả lớp', 'cùng', 'làm', 'báo tường.'], ['Lá tre', 'xào xạc', 'trong', 'gió chiều.'], ['Mẹ', 'ru', 'em', 'ngủ.'], ['Chim', 'ríu rít', 'trên', 'khóm tre.'], ['Cô giáo', 'rất', 'xúc động.']],
 PUNCT=[('Cô giáo nói ☐ “Đây là món quà ý nghĩa nhất.”', ':', [':', '?', '!']), ('Ai đã vẽ bó hoa này ☐', '?', None), ('Ôi, tờ báo đẹp quá ☐', '!', None), ('Khóm tre đầu ngõ xanh mát quanh năm ☐', '.', None), ('Bạn có thích nghe mẹ ru không ☐', '?', None), ('Chà, bóng tre mát thật ☐', '!', None)]))

# ===================== TẬP 2 · UỐNG NƯỚC NHỚ NGUỒN =====================
U.append(dict(lab='Chặng 11', t='Sự tích con Rồng cháu Tiên · Cảm xúc Trường Sa · Sáng tháng Năm · Chàng trai làng Phù Ủng', vn='Bài 9 – 12 · Tập 2 · Uống nước nhớ nguồn',
 A=[P('Con Rồng cháu Tiên', 'Ngày xưa, Lạc Long Quân thuộc nòi rồng, sống dưới nước, kết duyên cùng nàng Âu Cơ thuộc dòng tiên ở trên núi. Âu Cơ sinh ra một cái bọc trăm trứng, nở ra một trăm người con khoẻ mạnh. Sau đó, năm mươi người con theo cha xuống biển, năm mươi người con theo mẹ lên núi, chia nhau cai quản các phương. Người con trưởng được tôn lên làm vua, lấy hiệu là Hùng Vương. Vì thế, người Việt Nam tự hào mình là con Rồng cháu Tiên.',
   [('Lạc Long Quân thuộc nòi gì?', 'Nòi rồng', ['Dòng tiên', 'Dòng chim']),
    ('Âu Cơ sinh ra vật gì?', 'Một cái bọc trăm trứng', ['Một quả bầu', 'Một con rồng']),
    ('Bao nhiêu người con theo mẹ lên núi?', 'Năm mươi người', ['Một trăm người', 'Hai mươi người']),
    ('Người con trưởng lấy hiệu là gì?', 'Hùng Vương', ['Lý Thái Tổ', 'An Dương Vương']),
    ('Người Việt Nam tự hào mình là gì?', 'Con Rồng cháu Tiên', ['Con cháu thần Mặt Trời', 'Con cháu thần Núi'])]),
  P('Chàng trai ngồi đan sọt', 'Làng Phù Ủng có một chàng trai tên là Phạm Ngũ Lão. Một hôm, chàng ngồi bên vệ đường đan sọt, mải nghĩ về việc nước nên không biết đoàn quân của Hưng Đạo Vương đi qua. Quân lính lấy giáo đâm vào đùi, chàng vẫn không nhúc nhích. Hưng Đạo Vương lấy làm lạ, hỏi chuyện. Thấy chàng là người có chí lớn, ông liền đưa về kinh đô. Về sau, Phạm Ngũ Lão trở thành một vị tướng giỏi, lập nhiều chiến công chống giặc ngoại xâm.',
   [('Phạm Ngũ Lão quê ở đâu?', 'Làng Phù Ủng', ['Làng Gióng', 'Làng Sen']),
    ('Khi đoàn quân đi qua, chàng đang làm gì?', 'Ngồi đan sọt bên vệ đường', ['Cày ruộng', 'Đọc sách']),
    ('Vì sao chàng không biết đoàn quân đi qua?', 'Vì mải nghĩ về việc nước', ['Vì đang ngủ', 'Vì bị điếc']),
    ('Ai đã đưa chàng về kinh đô?', 'Hưng Đạo Vương', ['Vua Hùng', 'Lý Công Uẩn']),
    ('Về sau Phạm Ngũ Lão trở thành ai?', 'Một vị tướng giỏi', ['Một thầy thuốc', 'Một nhà buôn'])])],
 AV=[('Câu tục ngữ “Uống nước nhớ nguồn” khuyên gì?', 'Biết ơn những người đi trước', ['Nên uống nhiều nước', 'Phải tìm nguồn nước']),
     ('Quần đảo Trường Sa thuộc vùng biển nào của nước ta?', 'Biển Đông', ['Biển Bắc', 'Biển Chết']),
     ('Ngày 19 tháng 5 là ngày sinh của ai?', 'Chủ tịch Hồ Chí Minh', ['Vua Hùng', 'Trần Hưng Đạo']),
     ('Ngày Giỗ Tổ Hùng Vương là ngày nào?', 'Mùng 10 tháng 3 âm lịch', ['Mùng 1 tháng 1 âm lịch', 'Ngày 2 tháng 9']),
     ('Từ nào chỉ lòng biết ơn tổ tiên?', 'Tri ân', ['Vô ơn', 'Quên lãng']),
     ('“Đồng bào” nghĩa là gì?', 'Người cùng một nước, cùng giống nòi', ['Người cùng một trường', 'Người cùng một nhà'])],
 W=dict(dt=['bọc trứng', 'kinh đô', 'vị tướng', 'hòn đảo', 'chiến công', 'giặc ngoại xâm'], dgt=['kết duyên', 'cai quản', 'đan', 'lập', 'canh giữ', 'nhúc nhích'], tt=['khoẻ mạnh', 'hiên ngang', 'lừng lẫy', 'kiên cường', 'bao la', 'thiêng liêng']),
 TC=[('Trạng ngữ là gì?', 'Thành phần phụ, bổ sung thời gian, nơi chốn, nguyên nhân… cho câu', ['Thành phần chính của câu', 'Từ chỉ tên riêng']),
     ('Trạng ngữ thường đứng ở đâu trong câu?', 'Đầu câu, ngăn cách với chủ ngữ bằng dấu phẩy', ['Cuối câu, sau dấu chấm', 'Giữa hai tiếng của một từ']),
     ('Trạng ngữ chỉ thời gian trả lời câu hỏi nào?', 'Khi nào?', ['Ở đâu?', 'Vì sao?']),
     ('Trạng ngữ chỉ nơi chốn trả lời câu hỏi nào?', 'Ở đâu?', ['Khi nào?', 'Để làm gì?']),
     ('Câu nào có trạng ngữ?', 'Ngày xưa, Âu Cơ sinh ra bọc trăm trứng.', ['Âu Cơ sinh ra bọc trăm trứng.', 'Bọc trứng nở ra trăm con.']),
     ('Tên người nào viết đúng?', 'Phạm Ngũ Lão', ['Phạm ngũ lão', 'phạm Ngũ Lão'])],
 CT=[('Trường Sa', 'Chường Sa'), ('Lạc Long Quân', 'Lạc long quân'), ('giặc ngoại xâm', 'dặc ngoại xâm'), ('đan sọt', 'đan xọt'), ('nhúc nhích', 'nhúc nhít'), ('Hưng Đạo Vương', 'Hưng đạo vương'), ('xuống biển', 'suống biển')],
 CAU=[('Ngày xưa', 'tg', 'Lạc Long Quân', 'kết duyên cùng Âu Cơ.'), ('Bên vệ đường', 'nc', 'Phạm Ngũ Lão', 'ngồi đan sọt.'), ('Ngoài đảo xa', 'nc', 'các chú bộ đội', 'canh giữ biển trời.'),
      ('Sáng tháng Năm', 'tg', 'Bác Hồ', 'đi thăm các cháu thiếu nhi.'), ('Vì mải nghĩ việc nước', 'ng', 'chàng trai', 'không biết đoàn quân đi qua.'), ('Để nhớ ơn tổ tiên', 'md', 'người Việt', 'tổ chức Giỗ Tổ Hùng Vương.')],
 ORD=[['Ngày xưa,', 'Âu Cơ', 'sinh ra', 'bọc trăm trứng.'], ['Phạm Ngũ Lão', 'ngồi', 'đan sọt', 'bên đường.'], ['Các chú bộ đội', 'canh giữ', 'đảo', 'Trường Sa.'], ['Người Việt', 'là', 'con Rồng', 'cháu Tiên.'], ['Năm mươi người con', 'theo cha', 'xuống biển.']],
 PUNCT=[('Ngày xưa ☐ Lạc Long Quân kết duyên cùng Âu Cơ.', ',', [',', '.', '?']), ('Ngoài đảo xa ☐ các chú bộ đội ngày đêm canh giữ.', ',', [',', '!', '?']),
        ('Hưng Đạo Vương hỏi ☐ “Ngươi đang nghĩ gì?”', ':', [':', ',', '!']), ('Vì sao chàng trai không nhúc nhích ☐', '?', None), ('Ôi, Trường Sa đẹp quá ☐', '!', None), ('Người Việt Nam là con Rồng cháu Tiên ☐', '.', None)]))

U.append(dict(lab='Chặng 12', t='Vườn của ông tôi · Trong lời mẹ hát · Người thầy đầu tiên của bố tôi · Ngựa biên phòng', vn='Bài 13 – 16 · Tập 2 · Uống nước nhớ nguồn',
 A=[P('Khu vườn của ông', 'Ông tôi có một khu vườn nhỏ sau nhà. Mỗi sáng, ông dậy từ rất sớm để tưới cây, nhổ cỏ. Nhờ bàn tay chăm chút của ông, vườn lúc nào cũng xanh tốt. Mùa xuân, hoa bưởi thơm ngan ngát. Mùa hè, những chùm vải chín đỏ trĩu cành. Ông bảo: “Cây cũng như người, được chăm sóc thì sẽ đền đáp.” Giờ ông đã già, tôi xin ông cho tôi cùng chăm vườn. Tôi muốn giữ mãi khu vườn như giữ những lời dạy của ông.',
   [('Khu vườn của ông ở đâu?', 'Sau nhà', ['Trước cổng làng', 'Trên đồi']),
    ('Mỗi sáng ông làm gì?', 'Tưới cây, nhổ cỏ', ['Đi chợ', 'Đọc báo']),
    ('Mùa hè, trong vườn có gì?', 'Những chùm vải chín đỏ', ['Hoa bưởi thơm', 'Hoa đào nở']),
    ('Ông so sánh cây với gì?', 'Với con người', ['Với con vật', 'Với ngôi nhà']),
    ('Bạn nhỏ muốn giữ khu vườn như giữ điều gì?', 'Những lời dạy của ông', ['Những món đồ chơi', 'Những bức ảnh'])]),
  P('Chú ngựa nơi biên giới', 'Trên con đường tuần tra dọc biên giới, chú ngựa Hồng luôn đi cùng các chú bộ đội. Đường núi dốc đứng, đá lởm chởm, xe không đi được thì ngựa Hồng thồ hàng, thồ gạo. Mùa đông, sương muối phủ trắng, Hồng vẫn bước đều. Có lần, một chú bộ đội bị ngã, Hồng đứng im chờ cho chú vịn vào lưng mình. Các chú thương Hồng như một người đồng đội. Ai cũng gọi Hồng là “chiến sĩ biên phòng bốn chân”.',
   [('Ngựa Hồng làm việc ở đâu?', 'Dọc biên giới', ['Trong thành phố', 'Ngoài hải đảo']),
    ('Khi xe không đi được, ngựa Hồng làm gì?', 'Thồ hàng, thồ gạo', ['Chạy đi chơi', 'Đứng nghỉ']),
    ('Mùa đông ở biên giới có gì?', 'Sương muối phủ trắng', ['Nắng gắt', 'Lũ lụt']),
    ('Khi chú bộ đội bị ngã, Hồng làm gì?', 'Đứng im chờ chú vịn vào lưng', ['Bỏ chạy', 'Hí vang']),
    ('Mọi người gọi Hồng là gì?', 'Chiến sĩ biên phòng bốn chân', ['Ngựa đua nhanh nhất', 'Ngựa của nhà vua'])])],
 AV=[('“Biên phòng” là gì?', 'Bảo vệ vùng biên giới', ['Một căn phòng nhỏ', 'Vùng giữa đất nước']),
     ('Câu “Ăn quả nhớ kẻ trồng cây” khuyên gì?', 'Nhớ ơn người đã làm ra thành quả', ['Nên ăn nhiều hoa quả', 'Phải trồng cây ăn quả']),
     ('Người thầy đầu tiên thường dạy ta điều gì?', 'Những con chữ và bài học đầu đời', ['Cách kiếm tiền', 'Cách chơi điện tử']),
     ('Lời mẹ hát (ca dao, lời ru) giúp con điều gì?', 'Hiểu thêm về quê hương, con người', ['Biết làm toán nhanh', 'Biết lái xe']),
     ('Từ nào chỉ sự kính trọng thầy cô?', 'Tôn sư trọng đạo', ['Vô lễ', 'Coi thường']),
     ('“Đồng đội” là gì?', 'Người cùng chiến đấu, cùng làm nhiệm vụ', ['Người cùng họ', 'Người hàng xóm'])],
 W=dict(dt=['khu vườn', 'hoa bưởi', 'biên giới', 'sương muối', 'đồng đội', 'thầy giáo'], dgt=['tưới', 'nhổ', 'chăm sóc', 'tuần tra', 'thồ', 'vịn'], tt=['ngan ngát', 'um tùm', 'dốc đứng', 'lởm chởm', 'xanh tốt', 'vững chãi']),
 TC=[('Trạng ngữ chỉ nguyên nhân trả lời câu hỏi nào?', 'Vì sao? Nhờ đâu? Tại sao?', ['Khi nào?', 'Ở đâu?']),
     ('Trạng ngữ chỉ mục đích trả lời câu hỏi nào?', 'Để làm gì? Nhằm mục đích gì?', ['Vì sao?', 'Bằng gì?']),
     ('Trạng ngữ trong câu “Nhờ bàn tay chăm chút của ông, vườn lúc nào cũng xanh tốt.” chỉ gì?', 'Nguyên nhân', ['Thời gian', 'Nơi chốn']),
     ('Trạng ngữ trong câu “Mùa xuân, hoa bưởi thơm ngan ngát.” chỉ gì?', 'Thời gian', ['Mục đích', 'Nguyên nhân']),
     ('Trạng ngữ trong câu “Để bảo vệ biên giới, các chú bộ đội tuần tra ngày đêm.” chỉ gì?', 'Mục đích', ['Thời gian', 'Nơi chốn']),
     ('Câu nào có trạng ngữ chỉ nơi chốn?', 'Trên đường tuần tra, ngựa Hồng bước đều.', ['Mùa đông, sương phủ trắng.', 'Vì trời mưa, đường trơn.'])],
 CT=[('biên giới', 'biên dới'), ('sương muối', 'xương muối'), ('tuần tra', 'tuần cha'), ('ngan ngát', 'ngan ngác'), ('lởm chởm', 'lởm chổm'), ('trĩu cành', 'chĩu cành'), ('chăm chút', 'chăm trút')],
 CAU=[('Mỗi sáng', 'tg', 'ông', 'tưới cây, nhổ cỏ.'), ('Nhờ bàn tay chăm chút của ông', 'ng', 'khu vườn', 'luôn xanh tốt.'), ('Mùa hè', 'tg', 'những chùm vải', 'chín đỏ trĩu cành.'),
      ('Trên đường tuần tra', 'nc', 'ngựa Hồng', 'bước đều.'), ('Để bảo vệ biên giới', 'md', 'các chú bộ đội', 'tuần tra ngày đêm.'), ('Vì đường núi dốc đứng', 'ng', 'xe', 'không đi được.')],
 ORD=[['Mùa xuân,', 'hoa bưởi', 'thơm', 'ngan ngát.'], ['Ngựa Hồng', 'thồ', 'gạo', 'lên núi.'], ['Ông', 'chăm sóc', 'khu vườn', 'mỗi sáng.'], ['Mẹ', 'hát', 'ru', 'con', 'ngủ.'], ['Em', 'luôn', 'nhớ ơn', 'thầy cô.']],
 PUNCT=[('Mùa đông ☐ sương muối phủ trắng biên giới.', ',', [',', '?', '!']), ('Nhờ bàn tay của ông ☐ khu vườn luôn xanh tốt.', ',', [',', '.', '?']),
        ('Ông bảo ☐ “Cây cũng như người.”', ':', [':', '?', '!']), ('Ngựa Hồng có mệt không ☐', '?', None), ('Ôi, những chùm vải chín đỏ quá ☐', '!', None), ('Các chú bộ đội thương ngựa Hồng như đồng đội ☐', '.', None)]))
