from tv4c import P, U

# ===================== TẬP 2 · QUÊ HƯƠNG TRONG TÔI =====================
U.append(dict(lab='Chặng 13', t='Cây đa quê hương · Bước mùa xuân · Đi hội chùa Hương · Chiều ngoại ô', vn='Bài 17 – 20 · Tập 2 · Quê hương trong tôi',
 A=[P('Cây đa đầu làng', 'Ở đầu làng em có một cây đa cổ thụ. Thân cây to đến mấy người ôm không xuể, rễ buông xuống như những bộ râu dài. Tán đa xoè rộng như chiếc ô khổng lồ che mát cả một khoảng sân. Chiều chiều, bọn trẻ chăn trâu ngồi dưới gốc đa thổi sáo, kể chuyện. Người đi xa trở về, nhìn thấy cây đa là biết đã về đến làng. Với mọi người, cây đa như một người già hiền hậu, lặng lẽ canh giữ làng quê.',
   [('Cây đa ở đâu?', 'Đầu làng', ['Giữa chợ', 'Trong sân trường']),
    ('Rễ đa được ví với gì?', 'Những bộ râu dài', ['Những sợi chỉ', 'Những con rắn']),
    ('Tán đa xoè rộng như gì?', 'Chiếc ô khổng lồ', ['Cánh buồm', 'Mái nhà tranh']),
    ('Chiều chiều, bọn trẻ làm gì dưới gốc đa?', 'Thổi sáo, kể chuyện', ['Học bài', 'Đi chợ']),
    ('Cây đa được ví như ai?', 'Một người già hiền hậu', ['Một em bé', 'Một người lính trẻ'])]),
  P('Đi hội mùa xuân', 'Mùa xuân, cả nhà em về quê đi hội. Con đường làng rộn ràng tiếng trống, cờ ngũ sắc bay phấp phới. Ở sân đình, các cụ chơi cờ người, thanh niên thi kéo co, đấu vật. Em thích nhất là trò đu tiên, chiếc đu bay vút lên cao giữa tiếng reo hò. Mẹ kể rằng lễ hội là dịp để mọi người cầu mong một năm mưa thuận gió hoà, mùa màng tươi tốt. Em thấy quê hương mình thật đẹp và đáng yêu.',
   [('Cả nhà em về quê khi nào?', 'Mùa xuân', ['Mùa hè', 'Mùa đông']),
    ('Ở sân đình, các cụ chơi trò gì?', 'Cờ người', ['Kéo co', 'Đu tiên']),
    ('Bạn nhỏ thích nhất trò chơi nào?', 'Đu tiên', ['Đấu vật', 'Cờ người']),
    ('Lễ hội là dịp để mọi người cầu mong điều gì?', 'Mưa thuận gió hoà, mùa màng tươi tốt', ['Được đi du lịch', 'Được nghỉ học']),
    ('Cờ ngũ sắc có mấy màu?', 'Năm màu', ['Ba màu', 'Bảy màu'])])],
 AV=[('Cây đa, bến nước, sân đình thường gắn với hình ảnh nào?', 'Làng quê Việt Nam', ['Thành phố hiện đại', 'Sa mạc']),
     ('Chùa Hương nổi tiếng với dòng suối nào?', 'Suối Yến', ['Suối Tiên', 'Suối Mơ']),
     ('“Ngoại ô” là vùng nào?', 'Vùng ven, bên ngoài thành phố', ['Trung tâm thành phố', 'Giữa biển']),
     ('Từ nào chỉ không khí lễ hội?', 'Tưng bừng', ['Vắng lặng', 'Buồn tẻ']),
     ('“Cổ thụ” là cây thế nào?', 'Cây sống rất lâu năm, to lớn', ['Cây mới trồng', 'Cây cảnh nhỏ']),
     ('Câu “Quê hương là chùm khế ngọt” thể hiện tình cảm gì?', 'Yêu quê hương', ['Thích ăn khế', 'Nhớ trường học'])],
 W=dict(dt=['cây đa', 'tán lá', 'sân đình', 'lễ hội', 'cờ ngũ sắc', 'làng quê'], dgt=['buông', 'che', 'thổi', 'kéo co', 'đấu vật', 'cầu mong'], tt=['mát rượi', 'khổng lồ', 'rộn ràng', 'phấp phới', 'hiền hậu', 'tưng bừng']),
 TC=[('Dấu ngoặc kép dùng để làm gì?', 'Đánh dấu lời nói trực tiếp hoặc từ ngữ được dẫn lại', ['Kết thúc câu kể', 'Ngăn cách trạng ngữ']),
     ('Câu nào dùng dấu ngoặc kép đúng?', 'Mẹ bảo: “Con đi hội vui nhé!”', ['Mẹ bảo “: Con đi hội vui nhé!', 'Mẹ “bảo”: Con đi hội vui nhé!']),
     ('Trong câu “Chiều chiều, bọn trẻ ngồi dưới gốc đa.”, trạng ngữ là:', 'Chiều chiều', ['bọn trẻ', 'dưới gốc đa']),
     ('Trạng ngữ trong câu “Ở sân đình, các cụ chơi cờ người.” chỉ gì?', 'Nơi chốn', ['Thời gian', 'Nguyên nhân']),
     ('Từ nào có nghĩa là “nơi mình sinh ra, lớn lên”?', 'Quê hương', ['Phố phường', 'Nước ngoài']),
     ('Tên địa danh nào viết đúng?', 'Chùa Hương', ['chùa hương', 'Chùa hương'])],
 CT=[('cổ thụ', 'cỗ thụ'), ('xoè rộng', 'soè rộng'), ('phấp phới', 'phấp phơi'), ('rộn ràng', 'rộn dàng'), ('sân đình', 'xân đình'), ('suối Yến', 'suối yến'), ('ngũ sắc', 'ngủ sắc')],
 CAU=[('Ở đầu làng', 'nc', 'cây đa cổ thụ', 'toả bóng mát.'), ('Chiều chiều', 'tg', 'bọn trẻ', 'ngồi dưới gốc đa thổi sáo.'), ('Mùa xuân', 'tg', 'cả nhà em', 'về quê đi hội.'),
      ('Ở sân đình', 'nc', 'các cụ', 'chơi cờ người.'), ('Để cầu mong mùa màng tươi tốt', 'md', 'dân làng', 'mở hội mùa xuân.'), ('', '', 'Chiếc đu', 'bay vút lên cao.')],
 ORD=[['Cây đa', 'toả', 'bóng mát', 'đầu làng.'], ['Cờ', 'ngũ sắc', 'bay', 'phấp phới.'], ['Chiều chiều,', 'bọn trẻ', 'thổi sáo', 'dưới gốc đa.'], ['Em', 'yêu', 'quê hương', 'của mình.'], ['Thanh niên', 'thi', 'kéo co', 'ở sân đình.']],
 PUNCT=[('Chiều chiều ☐ bọn trẻ ngồi dưới gốc đa thổi sáo.', ',', [',', '?', '!']), ('Mẹ dặn ☐ “Con đi hội nhớ theo sát bố mẹ nhé!”', ':', [':', ',', '?']),
        ('Ở sân đình ☐ các cụ chơi cờ người.', ',', [',', '.', '!']), ('Ôi, lễ hội vui quá ☐', '!', None), ('Bạn đã đi hội chùa Hương chưa ☐', '?', None), ('Cây đa đầu làng đã có từ rất lâu ☐', '.', None)]))

U.append(dict(lab='Chặng 14', t='Những cánh buồm · Cây trái trong vườn Bác · Đường đi Sa Pa · Quê ngoại', vn='Bài 21 – 24 · Tập 2 · Quê hương trong tôi',
 A=[P('Đường lên Sa Pa', 'Sa Pa là một thị trấn nghỉ mát nằm trên núi cao của tỉnh Lào Cai. Xe ô tô leo mãi những con dốc quanh co, hai bên là mây trắng bồng bềnh. Những thửa ruộng bậc thang uốn lượn như những bậc thang khổng lồ lên tận trời xanh. Trong một ngày, thời tiết Sa Pa thay đổi liên tục: sáng mát lạnh, trưa nắng vàng, chiều lại có sương mù. Người ta ví Sa Pa như một món quà tặng kì diệu mà thiên nhiên dành cho đất nước ta.',
   [('Sa Pa thuộc tỉnh nào?', 'Lào Cai', ['Lâm Đồng', 'Quảng Ninh']),
    ('Hai bên đường lên Sa Pa có gì?', 'Mây trắng bồng bềnh', ['Biển xanh', 'Nhà cao tầng']),
    ('Ruộng bậc thang được ví như gì?', 'Những bậc thang khổng lồ lên trời', ['Những con sóng', 'Những chiếc lá']),
    ('Thời tiết Sa Pa trong một ngày thế nào?', 'Thay đổi liên tục', ['Lúc nào cũng nóng', 'Lúc nào cũng mưa']),
    ('Sa Pa được ví như gì?', 'Món quà kì diệu của thiên nhiên', ['Một thành phố ồn ào', 'Một sa mạc khô cằn'])]),
  P('Mùa hè ở quê ngoại', 'Hè năm nào em cũng về quê ngoại. Quê ngoại có con sông hiền hoà, nước trong vắt nhìn thấy cả đàn cá nhỏ. Buổi sáng, em theo ngoại ra đồng thăm lúa. Buổi chiều, em cùng các bạn thả diều trên đê, những cánh diều no gió bay cao vút. Tối đến, ngoại kể chuyện cổ tích bên hiên nhà, gió sông thổi vào mát rượi. Mỗi lần xa quê ngoại, em lại mong mùa hè năm sau đến thật nhanh.',
   [('Em về quê ngoại vào dịp nào?', 'Mùa hè', ['Tết Nguyên đán', 'Tết Trung thu']),
    ('Nước sông quê ngoại như thế nào?', 'Trong vắt', ['Đục ngầu', 'Đen kịt']),
    ('Buổi chiều em làm gì?', 'Thả diều trên đê', ['Đi bơi ở biển', 'Học đàn']),
    ('Tối đến, ngoại làm gì?', 'Kể chuyện cổ tích', ['Xem ti vi', 'Đi chợ đêm']),
    ('Khi xa quê ngoại, em mong điều gì?', 'Mùa hè năm sau đến thật nhanh', ['Không phải về quê nữa', 'Được đi học ngay'])])],
 AV=[('Ruộng bậc thang thường có ở đâu?', 'Vùng núi cao', ['Vùng biển', 'Giữa thành phố']),
     ('“Cánh buồm” giúp con thuyền làm gì?', 'Đón gió để đi', ['Chìm xuống nước', 'Chở thêm hàng']),
     ('Vườn cây của Bác Hồ ở Phủ Chủ tịch có nhiều cây trái từ đâu gửi tặng?', 'Khắp các miền đất nước', ['Chỉ từ Hà Nội', 'Chỉ từ nước ngoài']),
     ('Từ nào tả mây trôi nhẹ nhàng?', 'Bồng bềnh', ['Ầm ầm', 'Lạnh buốt']),
     ('“Quê ngoại” là quê của ai?', 'Của mẹ', ['Của bố', 'Của bạn']),
     ('Từ nào gợi tả con đường nhiều khúc quanh?', 'Quanh co', ['Thẳng tắp', 'Bằng phẳng'])],
 W=dict(dt=['thị trấn', 'ruộng bậc thang', 'sương mù', 'cánh diều', 'con đê', 'hiên nhà'], dgt=['leo', 'uốn lượn', 'thả', 'kể', 'thăm', 'mong'], tt=['quanh co', 'bồng bềnh', 'trong vắt', 'hiền hoà', 'cao vút', 'mát lạnh']),
 TC=[('Dấu ngoặc đơn dùng để làm gì?', 'Đánh dấu phần chú thích, giải thích thêm', ['Kết thúc câu hỏi', 'Đánh dấu lời nói']),
     ('Câu nào dùng dấu ngoặc đơn đúng?', 'Sa Pa (Lào Cai) là nơi nghỉ mát nổi tiếng.', ['Sa Pa là (nơi nghỉ) mát nổi tiếng.', '(Sa Pa) là nơi nghỉ mát (nổi tiếng).']),
     ('Trạng ngữ trong câu “Buổi sáng, em theo ngoại ra đồng.” là:', 'Buổi sáng', ['em', 'ra đồng']),
     ('Trạng ngữ trong câu “Bằng chiếc xe khách, chúng em lên Sa Pa.” chỉ gì?', 'Phương tiện', ['Thời gian', 'Nơi chốn']),
     ('Trạng ngữ chỉ phương tiện trả lời câu hỏi nào?', 'Bằng gì? Với cái gì?', ['Khi nào?', 'Vì sao?']),
     ('Tên địa danh nào viết đúng?', 'Lào Cai', ['Lào cai', 'lào Cai'])],
 CT=[('Sa Pa', 'Xa Pa'), ('bậc thang', 'bật thang'), ('uốn lượn', 'uốn lựơn'), ('sương mù', 'xương mù'), ('trong vắt', 'trong vắc'), ('diều giấy', 'giều giấy'), ('bồng bềnh', 'bồng bền')],
 CAU=[('Trên núi cao', 'nc', 'ruộng bậc thang', 'uốn lượn.'), ('Buổi sáng', 'tg', 'em', 'theo ngoại ra đồng.'), ('Bằng chiếc xe khách', 'pt', 'chúng em', 'lên Sa Pa.'),
      ('Tối đến', 'tg', 'ngoại', 'kể chuyện cổ tích.'), ('Nhờ có gió', 'ng', 'những cánh diều', 'bay cao vút.'), ('Trên con sông quê', 'nc', 'những cánh buồm', 'lướt nhẹ.')],
 ORD=[['Sa Pa', 'là', 'một', 'thị trấn', 'nghỉ mát.'], ['Buổi chiều,', 'em', 'thả diều', 'trên đê.'], ['Mây trắng', 'bồng bềnh', 'trên', 'đỉnh núi.'], ['Ngoại', 'kể', 'chuyện cổ tích', 'bên hiên nhà.'], ['Con sông', 'quê ngoại', 'thật', 'hiền hoà.']],
 PUNCT=[('Buổi sáng ☐ em theo ngoại ra đồng.', ',', [',', '?', '!']), ('Bằng chiếc xe khách ☐ chúng em lên Sa Pa.', ',', [',', '.', '!']),
        ('Ngoại hỏi ☐ “Cháu có thích thả diều không?”', ':', [':', ',', '!']), ('Sa Pa có đẹp không hả mẹ ☐', '?', None), ('Ôi, ruộng bậc thang đẹp quá ☐', '!', None), ('Hè năm nào em cũng về quê ngoại ☐', '.', None)]))

# ===================== TẬP 2 · VÌ MỘT THẾ GIỚI BÌNH YÊN =====================
U.append(dict(lab='Chặng 15', t='Khu bảo tồn động vật hoang dã Ngô-rông-gô-rô · Ngôi nhà của yêu thương · Băng tan', vn='Bài 25 – 27 · Tập 2 · Vì một thế giới bình yên',
 A=[P('Vùng đất của muông thú', 'Ngô-rông-gô-rô là một khu bảo tồn động vật hoang dã nổi tiếng ở châu Phi. Nơi đây có đồng cỏ mênh mông, hồ nước trong xanh và rất nhiều loài vật. Những đàn ngựa vằn thong thả gặm cỏ. Voi dẫn đàn con đi tìm nước. Sư tử nằm lim dim dưới bóng cây. Người ta lập khu bảo tồn để bảo vệ các loài vật, giữ cho chúng được sống tự do trong môi trường tự nhiên. Du khách đến đây phải giữ yên lặng và không được cho thú ăn.',
   [('Ngô-rông-gô-rô ở châu lục nào?', 'Châu Phi', ['Châu Á', 'Châu Âu']),
    ('Đàn ngựa vằn đang làm gì?', 'Thong thả gặm cỏ', ['Chạy trốn thợ săn', 'Tắm biển']),
    ('Sư tử làm gì dưới bóng cây?', 'Nằm lim dim', ['Leo lên cây', 'Đào hang']),
    ('Người ta lập khu bảo tồn để làm gì?', 'Bảo vệ các loài vật', ['Để săn bắn', 'Để xây nhà máy']),
    ('Du khách đến đây phải làm gì?', 'Giữ yên lặng, không cho thú ăn', ['Hò hét thật to', 'Cho thú ăn bánh kẹo'])]),
  P('Khi băng tan', 'Ở vùng Bắc Cực, những tảng băng khổng lồ là ngôi nhà của gấu trắng. Nhưng Trái Đất đang nóng dần lên, băng tan nhanh hơn trước rất nhiều. Gấu trắng phải bơi rất xa mới tìm được chỗ nghỉ chân. Nước biển dâng cao, nhiều vùng ven biển có thể bị ngập. Để bảo vệ Trái Đất, mỗi người có thể làm những việc nhỏ: tắt điện khi ra khỏi phòng, trồng thêm cây xanh, hạn chế dùng túi ni lông.',
   [('Ngôi nhà của gấu trắng ở Bắc Cực là gì?', 'Những tảng băng khổng lồ', ['Những hang đá', 'Những khu rừng']),
    ('Vì sao băng tan nhanh hơn trước?', 'Vì Trái Đất đang nóng dần lên', ['Vì có quá nhiều gấu', 'Vì trời mưa nhiều']),
    ('Gấu trắng gặp khó khăn gì?', 'Phải bơi rất xa mới có chỗ nghỉ chân', ['Không có gì để uống', 'Bị lạnh cóng']),
    ('Khi nước biển dâng cao, điều gì có thể xảy ra?', 'Nhiều vùng ven biển bị ngập', ['Sa mạc mọc thêm cây', 'Núi cao hơn']),
    ('Việc nào giúp bảo vệ Trái Đất?', 'Tắt điện khi ra khỏi phòng', ['Dùng nhiều túi ni lông', 'Chặt cây lấy gỗ'])])],
 AV=[('“Hoang dã” là gì?', 'Sống tự nhiên, không do con người nuôi', ['Được nuôi trong nhà', 'Được bán ở chợ']),
     ('Từ nào trái nghĩa với “chiến tranh”?', 'Hoà bình', ['Xung đột', 'Tàn phá']),
     ('Biểu tượng của hoà bình thường là con vật nào?', 'Chim bồ câu trắng', ['Chim đại bàng', 'Con sư tử']),
     ('Việc làm nào góp phần bảo vệ môi trường?', 'Phân loại rác', ['Xả rác xuống sông', 'Đốt rừng']),
     ('“Ngôi nhà của yêu thương” là nơi thế nào?', 'Nơi mọi người quan tâm, chăm sóc nhau', ['Nơi có nhiều đồ đắt tiền', 'Nơi không ai ở']),
     ('Từ nào đồng nghĩa với “bình yên”?', 'Yên bình', ['Hỗn loạn', 'Ồn ào'])],
 W=dict(dt=['khu bảo tồn', 'ngựa vằn', 'đồng cỏ', 'tảng băng', 'gấu trắng', 'Trái Đất'], dgt=['gặm', 'bảo vệ', 'tan', 'bơi', 'tắt', 'hạn chế'], tt=['hoang dã', 'mênh mông', 'thong thả', 'trong xanh', 'khổng lồ', 'yên bình']),
 TC=[('Tên châu lục nào viết đúng?', 'châu Phi', ['Châu phi', 'chầu Phi']),
     ('Tên riêng nước ngoài phiên âm được viết thế nào?', 'Viết hoa chữ cái đầu mỗi bộ phận, giữa các tiếng có gạch nối', ['Viết thường tất cả', 'Viết hoa tất cả các chữ cái']),
     ('Tên nào viết đúng?', 'Ngô-rông-gô-rô', ['Ngô rông gô rô', 'ngô-rông-gô-rô']),
     ('Câu “Hãy tắt điện khi ra khỏi phòng!” dùng để làm gì?', 'Đề nghị, yêu cầu', ['Hỏi', 'Kể lại sự việc']),
     ('Trạng ngữ trong câu “Ở vùng Bắc Cực, băng đang tan dần.” là:', 'Ở vùng Bắc Cực', ['băng', 'đang tan dần']),
     ('Trạng ngữ trong câu “Để bảo vệ Trái Đất, em trồng thêm cây xanh.” chỉ gì?', 'Mục đích', ['Nguyên nhân', 'Thời gian'])],
 CT=[('bảo tồn', 'bảo tồng'), ('hoang dã', 'hoang giã'), ('mênh mông', 'mêng mông'), ('lim dim', 'nim dim'), ('Bắc Cực', 'Bắc cực'), ('ni lông', 'li lông'), ('Trái Đất', 'trái đất')],
 CAU=[('Ở khu bảo tồn', 'nc', 'đàn ngựa vằn', 'thong thả gặm cỏ.'), ('Vì Trái Đất nóng lên', 'ng', 'băng', 'tan nhanh hơn trước.'), ('Để bảo vệ Trái Đất', 'md', 'chúng em', 'trồng thêm cây xanh.'),
      ('Dưới bóng cây', 'nc', 'sư tử', 'nằm lim dim.'), ('Mỗi tối', 'tg', 'cả nhà em', 'quây quần bên nhau.'), ('', '', 'Gấu trắng', 'bơi rất xa để tìm chỗ nghỉ.')],
 ORD=[['Voi mẹ', 'dẫn', 'đàn con', 'đi tìm nước.'], ['Băng', 'ở', 'Bắc Cực', 'đang tan.'], ['Em', 'tắt điện', 'khi', 'ra khỏi phòng.'], ['Chúng ta', 'cùng', 'bảo vệ', 'Trái Đất.'], ['Chim bồ câu', 'là', 'biểu tượng', 'của hoà bình.']],
 PUNCT=[('Ở vùng Bắc Cực ☐ băng đang tan dần.', ',', [',', '?', '!']), ('Hãy cùng nhau bảo vệ Trái Đất ☐', '!', ['!', '?', ',']), ('Vì sao băng lại tan ☐', '?', None),
        ('Để bảo vệ môi trường ☐ em phân loại rác.', ',', [',', '.', '?']), ('Khu bảo tồn có rất nhiều loài vật ☐', '.', None), ('Ôi, đàn ngựa vằn đẹp quá ☐', '!', None)]))

U.append(dict(lab='Chặng 16', t='Chuyến du lịch thú vị · Lễ hội ở Nhật Bản · Ngày hội · Ôn tập cuối năm', vn='Bài 28 – 30 · Tập 2 · Vì một thế giới bình yên',
 A=[P('Ngày hội ngắm hoa', 'Mỗi độ xuân về, người Nhật Bản lại háo hức đón mùa hoa anh đào. Khắp công viên, những tán hoa hồng phớt nở rộ như những đám mây. Các gia đình trải thảm ngồi dưới gốc cây, cùng nhau ăn uống, trò chuyện và ngắm hoa. Người ta gọi đó là lễ hội ngắm hoa. Khi gió thổi, cánh hoa rơi lả tả như mưa. Lễ hội giúp mọi người thêm yêu thiên nhiên và gắn bó với nhau hơn.',
   [('Người Nhật Bản đón mùa hoa gì?', 'Hoa anh đào', ['Hoa sen', 'Hoa mai']),
    ('Hoa anh đào có màu gì?', 'Hồng phớt', ['Vàng rực', 'Tím sẫm']),
    ('Các gia đình làm gì dưới gốc cây?', 'Ăn uống, trò chuyện, ngắm hoa', ['Chặt cây lấy gỗ', 'Thi chạy']),
    ('Khi gió thổi, cánh hoa rơi như gì?', 'Như mưa', ['Như tuyết đen', 'Như đá']),
    ('Lễ hội giúp mọi người điều gì?', 'Thêm yêu thiên nhiên, gắn bó với nhau', ['Kiếm được nhiều tiền', 'Quên việc học'])]),
  P('Chuyến đi Vịnh Hạ Long', 'Hè vừa rồi, lớp em được đi tham quan vịnh Hạ Long. Con tàu trắng chở chúng em lướt trên mặt nước xanh biếc. Hàng nghìn hòn đảo lớn nhỏ nhô lên với đủ hình thù: hòn giống con gà, hòn như cái đỉnh hương. Chúng em vào thăm một hang động, những khối thạch nhũ lấp lánh dưới ánh đèn. Cô giáo cho biết vịnh Hạ Long là di sản thiên nhiên thế giới. Em tự nhủ phải cùng mọi người giữ gìn cảnh đẹp này.',
   [('Lớp em đi tham quan ở đâu?', 'Vịnh Hạ Long', ['Vịnh Nha Trang', 'Hồ Gươm']),
    ('Mặt nước vịnh có màu gì?', 'Xanh biếc', ['Đỏ thẫm', 'Vàng đục']),
    ('Các hòn đảo có hình thù thế nào?', 'Đủ hình thù: con gà, đỉnh hương', ['Hòn nào cũng tròn', 'Hòn nào cũng vuông']),
    ('Trong hang động có gì lấp lánh?', 'Những khối thạch nhũ', ['Những viên kim cương', 'Những ngọn nến']),
    ('Vịnh Hạ Long là gì?', 'Di sản thiên nhiên thế giới', ['Một khu vui chơi mới', 'Một hồ nước nhân tạo'])])],
 AV=[('“Du lịch” là gì?', 'Đi chơi, tham quan những nơi xa', ['Ở nhà nghỉ ngơi', 'Đi làm việc']),
     ('Vịnh Hạ Long thuộc tỉnh nào?', 'Quảng Ninh', ['Khánh Hoà', 'Lào Cai']),
     ('Khi đi du lịch, em nên làm gì?', 'Giữ gìn vệ sinh, bảo vệ cảnh quan', ['Khắc tên lên đá', 'Vứt rác xuống biển']),
     ('Từ nào cùng nghĩa với “háo hức”?', 'Nôn nao', ['Chán nản', 'Thờ ơ']),
     ('Ngày hội thường có không khí thế nào?', 'Vui tươi, náo nhiệt', ['Buồn bã, im lặng', 'Căng thẳng, sợ hãi']),
     ('Nhật Bản thuộc châu lục nào?', 'Châu Á', ['Châu Phi', 'Châu Mỹ'])],
 W=dict(dt=['hoa anh đào', 'công viên', 'hòn đảo', 'hang động', 'thạch nhũ', 'di sản'], dgt=['đón', 'trải', 'trò chuyện', 'tham quan', 'giữ gìn', 'nhô'], tt=['háo hức', 'hồng phớt', 'lả tả', 'xanh biếc', 'lấp lánh', 'náo nhiệt']),
 TC=[('Từ loại của “hòn đảo”, “tham quan”, “xanh biếc” lần lượt là:', 'Danh từ, động từ, tính từ', ['Động từ, danh từ, tính từ', 'Tính từ, động từ, danh từ']),
     ('Câu nào có trạng ngữ chỉ thời gian?', 'Hè vừa rồi, lớp em đi Hạ Long.', ['Lớp em đi Hạ Long bằng tàu.', 'Hạ Long rất đẹp.']),
     ('Câu nào dùng biện pháp nhân hoá?', 'Những hòn đảo đứng trầm ngâm giữa biển.', ['Những hòn đảo nhô lên giữa biển.', 'Biển có nhiều đảo.']),
     ('Dấu gạch ngang trong “chuyến bay Hà Nội – Tô-ky-ô” dùng để làm gì?', 'Nối các từ ngữ trong một liên danh', ['Đánh dấu lời nói', 'Kết thúc câu']),
     ('Tên nước nào viết đúng?', 'Nhật Bản', ['nhật Bản', 'Nhật bản']),
     ('Chủ ngữ của câu “Con tàu trắng lướt trên mặt nước.” là:', 'Con tàu trắng', ['lướt trên mặt nước', 'mặt nước'])],
 CT=[('anh đào', 'anh đàu'), ('lả tả', 'lã tã'), ('thạch nhũ', 'thạch nhủ'), ('xanh biếc', 'xanh biết'), ('di sản', 'gi sản'), ('háo hức', 'háu hức'), ('Hạ Long', 'Hạ long')],
 CAU=[('Mỗi độ xuân về', 'tg', 'người Nhật Bản', 'háo hức đón mùa hoa anh đào.'), ('Khắp công viên', 'nc', 'hoa anh đào', 'nở rộ.'), ('Hè vừa rồi', 'tg', 'lớp em', 'được đi tham quan vịnh Hạ Long.'),
      ('Bằng con tàu trắng', 'pt', 'chúng em', 'đi thăm các hòn đảo.'), ('Nhờ ánh đèn', 'ng', 'những khối thạch nhũ', 'lấp lánh.'), ('Để giữ gìn cảnh đẹp', 'md', 'du khách', 'không xả rác xuống vịnh.')],
 ORD=[['Hoa anh đào', 'nở', 'rộ', 'khắp công viên.'], ['Lớp em', 'tham quan', 'vịnh', 'Hạ Long.'], ['Cánh hoa', 'rơi', 'lả tả', 'như mưa.'], ['Chúng em', 'giữ gìn', 'cảnh đẹp', 'quê hương.'], ['Con tàu', 'lướt', 'trên', 'mặt nước', 'xanh biếc.']],
 PUNCT=[('Hè vừa rồi ☐ lớp em đi tham quan vịnh Hạ Long.', ',', [',', '?', '!']), ('Cô giáo nói ☐ “Hạ Long là di sản thiên nhiên thế giới.”', ':', [':', ',', '?']),
        ('Chuyến bay Hà Nội ☐ Tô-ky-ô cất cánh lúc 8 giờ.', '–', ['–', ',', '?']), ('Bạn đã đến Nhật Bản bao giờ chưa ☐', '?', None), ('Ôi, hoa anh đào đẹp quá ☐', '!', None), ('Vịnh Hạ Long có hàng nghìn hòn đảo ☐', '.', None)]))
